In [33]:
import models
from datasets import H5Dataset, SparseDataset
from single_model_trainer import Trainer

import pandas as pd
import torch
import torch.nn.functional as F

In [10]:
constant_cols = ['ENSG00000003137_CYP26B1', 'ENSG00000004848_ARX', 'ENSG00000006606_CCL26', 'ENSG00000010379_SLC6A13', 'ENSG00000010932_FMO1', 'ENSG00000017427_IGF1', 'ENSG00000022355_GABRA1', 'ENSG00000041982_TNC', 'ENSG00000060709_RIMBP2', 'ENSG00000064886_CHI3L2', 'ENSG00000065717_TLE2', 'ENSG00000067798_NAV3', 'ENSG00000069535_MAOB', 'ENSG00000073598_FNDC8', 'ENSG00000074219_TEAD2', 'ENSG00000074964_ARHGEF10L', 'ENSG00000077264_PAK3', 'ENSG00000078053_AMPH', 'ENSG00000082684_SEMA5B', 'ENSG00000083857_FAT1', 'ENSG00000084628_NKAIN1', 'ENSG00000084734_GCKR', 'ENSG00000086967_MYBPC2', 'ENSG00000087258_GNAO1', 'ENSG00000089505_CMTM1', 'ENSG00000091129_NRCAM', 'ENSG00000091986_CCDC80', 'ENSG00000092377_TBL1Y', 'ENSG00000092969_TGFB2', 'ENSG00000095397_WHRN', 'ENSG00000095970_TREM2', 'ENSG00000099715_PCDH11Y', 'ENSG00000100197_CYP2D6', 'ENSG00000100218_RSPH14', 'ENSG00000100311_PDGFB', 'ENSG00000100362_PVALB', 'ENSG00000100373_UPK3A', 'ENSG00000100625_SIX4', 'ENSG00000100867_DHRS2', 'ENSG00000100985_MMP9', 'ENSG00000101197_BIRC7', 'ENSG00000101298_SNPH', 'ENSG00000102387_TAF7L', 'ENSG00000103034_NDRG4', 'ENSG00000104059_FAM189A1', 'ENSG00000104112_SCG3', 'ENSG00000104313_EYA1', 'ENSG00000104892_KLC3', 'ENSG00000105088_OLFM2', 'ENSG00000105261_OVOL3', 'ENSG00000105290_APLP1', 'ENSG00000105507_CABP5', 'ENSG00000105642_KCNN1', 'ENSG00000105694_ELOCP28', 'ENSG00000105707_HPN', 'ENSG00000105894_PTN', 'ENSG00000106018_VIPR2', 'ENSG00000106541_AGR2', 'ENSG00000107317_PTGDS', 'ENSG00000108688_CCL7', 'ENSG00000108702_CCL1', 'ENSG00000108947_EFNB3', 'ENSG00000109193_SULT1E1', 'ENSG00000109794_FAM149A', 'ENSG00000109832_DDX25', 'ENSG00000110195_FOLR1', 'ENSG00000110375_UPK2', 'ENSG00000110436_SLC1A2', 'ENSG00000111339_ART4', 'ENSG00000111863_ADTRP', 'ENSG00000112761_WISP3', 'ENSG00000112852_PCDHB2', 'ENSG00000114251_WNT5A', 'ENSG00000114279_FGF12', 'ENSG00000114455_HHLA2', 'ENSG00000114757_PEX5L', 'ENSG00000115155_OTOF', 'ENSG00000115266_APC2', 'ENSG00000115297_TLX2', 'ENSG00000115590_IL1R2', 'ENSG00000115844_DLX2', 'ENSG00000116194_ANGPTL1', 'ENSG00000116661_FBXO2', 'ENSG00000116774_OLFML3', 'ENSG00000117322_CR2', 'ENSG00000117971_CHRNB4', 'ENSG00000118322_ATP10B', 'ENSG00000118402_ELOVL4', 'ENSG00000118520_ARG1', 'ENSG00000118946_PCDH17', 'ENSG00000118972_FGF23', 'ENSG00000119771_KLHL29', 'ENSG00000120549_KIAA1217', 'ENSG00000121316_PLBD1', 'ENSG00000121905_HPCA', 'ENSG00000122224_LY9', 'ENSG00000124194_GDAP1L1', 'ENSG00000124440_HIF3A', 'ENSG00000124657_OR2B6', 'ENSG00000125462_C1orf61', 'ENSG00000125895_TMEM74B', 'ENSG00000126838_PZP', 'ENSG00000128422_KRT17', 'ENSG00000128918_ALDH1A2', 'ENSG00000129170_CSRP3', 'ENSG00000129214_SHBG', 'ENSG00000129673_AANAT', 'ENSG00000129910_CDH15', 'ENSG00000130294_KIF1A', 'ENSG00000130307_USHBP1', 'ENSG00000130545_CRB3', 'ENSG00000131019_ULBP3', 'ENSG00000131044_TTLL9', 'ENSG00000131183_SLC34A1', 'ENSG00000131386_GALNT15', 'ENSG00000131400_NAPSA', 'ENSG00000131914_LIN28A', 'ENSG00000131941_RHPN2', 'ENSG00000131951_LRRC9', 'ENSG00000132170_PPARG', 'ENSG00000132681_ATP1A4', 'ENSG00000132958_TPTE2', 'ENSG00000133454_MYO18B', 'ENSG00000134545_KLRC1', 'ENSG00000134853_PDGFRA', 'ENSG00000135083_CCNJL', 'ENSG00000135100_HNF1A', 'ENSG00000135116_HRK', 'ENSG00000135312_HTR1B', 'ENSG00000135324_MRAP2', 'ENSG00000135436_FAM186B', 'ENSG00000135472_FAIM2', 'ENSG00000135898_GPR55', 'ENSG00000135929_CYP27A1', 'ENSG00000136002_ARHGEF4', 'ENSG00000136099_PCDH8', 'ENSG00000136274_NACAD', 'ENSG00000137078_SIT1', 'ENSG00000137142_IGFBPL1', 'ENSG00000137473_TTC29', 'ENSG00000137474_MYO7A', 'ENSG00000137491_SLCO2B1', 'ENSG00000137691_CFAP300', 'ENSG00000137731_FXYD2', 'ENSG00000137747_TMPRSS13', 'ENSG00000137878_GCOM1', 'ENSG00000138411_HECW2', 'ENSG00000138741_TRPC3', 'ENSG00000138769_CDKL2', 'ENSG00000138823_MTTP', 'ENSG00000139908_TSSK4', 'ENSG00000140832_MARVELD3', 'ENSG00000142178_SIK1', 'ENSG00000142538_PTH2', 'ENSG00000142910_TINAGL1', 'ENSG00000143217_NECTIN4', 'ENSG00000143858_SYT2', 'ENSG00000144130_NT5DC4', 'ENSG00000144214_LYG1', 'ENSG00000144290_SLC4A10', 'ENSG00000144366_GULP1', 'ENSG00000144583_MARCH4', 'ENSG00000144771_LRTM1', 'ENSG00000144891_AGTR1', 'ENSG00000145087_STXBP5L', 'ENSG00000145107_TM4SF19', 'ENSG00000146197_SCUBE3', 'ENSG00000146966_DENND2A', 'ENSG00000147082_CCNB3', 'ENSG00000147614_ATP6V0D2', 'ENSG00000147642_SYBU', 'ENSG00000147869_CER1', 'ENSG00000149403_GRIK4', 'ENSG00000149596_JPH2', 'ENSG00000150630_VEGFC', 'ENSG00000150722_PPP1R1C', 'ENSG00000151631_AKR1C6P', 'ENSG00000151704_KCNJ1', 'ENSG00000152154_TMEM178A', 'ENSG00000152292_SH2D6', 'ENSG00000152315_KCNK13', 'ENSG00000152503_TRIM36', 'ENSG00000153253_SCN3A', 'ENSG00000153902_LGI4', 'ENSG00000153930_ANKFN1', 'ENSG00000154040_CABYR', 'ENSG00000154118_JPH3', 'ENSG00000154175_ABI3BP', 'ENSG00000154645_CHODL', 'ENSG00000157060_SHCBP1L', 'ENSG00000157087_ATP2B2', 'ENSG00000157152_SYN2', 'ENSG00000157168_NRG1', 'ENSG00000157680_DGKI', 'ENSG00000158246_TENT5B', 'ENSG00000158477_CD1A', 'ENSG00000158481_CD1C', 'ENSG00000158488_CD1E', 'ENSG00000159189_C1QC', 'ENSG00000159217_IGF2BP1', 'ENSG00000160683_CXCR5', 'ENSG00000160801_PTH1R', 'ENSG00000160973_FOXH1', 'ENSG00000161594_KLHL10', 'ENSG00000162409_PRKAA2', 'ENSG00000162840_MT2P1', 'ENSG00000162873_KLHDC8A', 'ENSG00000162944_RFTN2', 'ENSG00000162949_CAPN13', 'ENSG00000163116_STPG2', 'ENSG00000163288_GABRB1', 'ENSG00000163531_NFASC', 'ENSG00000163618_CADPS', 'ENSG00000163637_PRICKLE2', 'ENSG00000163735_CXCL5', 'ENSG00000163873_GRIK3', 'ENSG00000163898_LIPH', 'ENSG00000164061_BSN', 'ENSG00000164078_MST1R', 'ENSG00000164123_C4orf45', 'ENSG00000164690_SHH', 'ENSG00000164761_TNFRSF11B', 'ENSG00000164821_DEFA4', 'ENSG00000164845_FAM86FP', 'ENSG00000164867_NOS3', 'ENSG00000166073_GPR176', 'ENSG00000166148_AVPR1A', 'ENSG00000166250_CLMP', 'ENSG00000166257_SCN3B', 'ENSG00000166268_MYRFL', 'ENSG00000166523_CLEC4E', 'ENSG00000166535_A2ML1', 'ENSG00000166819_PLIN1', 'ENSG00000166928_MS4A14', 'ENSG00000167210_LOXHD1', 'ENSG00000167306_MYO5B', 'ENSG00000167634_NLRP7', 'ENSG00000167748_KLK1', 'ENSG00000167889_MGAT5B', 'ENSG00000168140_VASN', 'ENSG00000168546_GFRA2', 'ENSG00000168646_AXIN2', 'ENSG00000168955_TM4SF20', 'ENSG00000168993_CPLX1', 'ENSG00000169075_Z99496.1', 'ENSG00000169194_IL13', 'ENSG00000169246_NPIPB3', 'ENSG00000169884_WNT10B', 'ENSG00000169900_PYDC1', 'ENSG00000170074_FAM153A', 'ENSG00000170075_GPR37L1', 'ENSG00000170289_CNGB3', 'ENSG00000170356_OR2A20P', 'ENSG00000170537_TMC7', 'ENSG00000170689_HOXB9', 'ENSG00000170827_CELP', 'ENSG00000171346_KRT15', 'ENSG00000171368_TPPP', 'ENSG00000171501_OR1N2', 'ENSG00000171532_NEUROD2', 'ENSG00000171611_PTCRA', 'ENSG00000171873_ADRA1D', 'ENSG00000171916_LGALS9C', 'ENSG00000172005_MAL', 'ENSG00000172987_HPSE2', 'ENSG00000173068_BNC2', 'ENSG00000173077_DEC1', 'ENSG00000173210_ABLIM3', 'ENSG00000173267_SNCG', 'ENSG00000173369_C1QB', 'ENSG00000173372_C1QA', 'ENSG00000173391_OLR1', 'ENSG00000173626_TRAPPC3L', 'ENSG00000173698_ADGRG2', 'ENSG00000173868_PHOSPHO1', 'ENSG00000174407_MIR1-1HG', 'ENSG00000174807_CD248', 'ENSG00000175206_NPPA', 'ENSG00000175746_C15orf54', 'ENSG00000175985_PLEKHD1', 'ENSG00000176043_AC007160.1', 'ENSG00000176399_DMRTA1', 'ENSG00000176510_OR10AC1', 'ENSG00000176697_BDNF', 'ENSG00000176826_FKBP9P1', 'ENSG00000176988_FMR1NB', 'ENSG00000177324_BEND2', 'ENSG00000177335_C8orf31', 'ENSG00000177535_OR2B11', 'ENSG00000177614_PGBD5', 'ENSG00000177707_NECTIN3', 'ENSG00000178033_CALHM5', 'ENSG00000178175_ZNF366', 'ENSG00000178462_TUBAL3', 'ENSG00000178732_GP5', 'ENSG00000178750_STX19', 'ENSG00000179058_C9orf50', 'ENSG00000179101_AL590139.1', 'ENSG00000179388_EGR3', 'ENSG00000179611_DGKZP1', 'ENSG00000179899_PHC1P1', 'ENSG00000179934_CCR8', 'ENSG00000180537_RNF182', 'ENSG00000180712_LINC02363', 'ENSG00000180988_OR52N2', 'ENSG00000181001_OR52N1', 'ENSG00000181616_OR52H1', 'ENSG00000181634_TNFSF15', 'ENSG00000182021_AL591379.1', 'ENSG00000182230_FAM153B', 'ENSG00000182853_VMO1', 'ENSG00000183090_FREM3', 'ENSG00000183562_AC131971.1', 'ENSG00000183615_FAM167B', 'ENSG00000183625_CCR3', 'ENSG00000183770_FOXL2', 'ENSG00000183779_ZNF703', 'ENSG00000183831_ANKRD45', 'ENSG00000183844_FAM3B', 'ENSG00000183960_KCNH8', 'ENSG00000184106_TREML3P', 'ENSG00000184227_ACOT1', 'ENSG00000184363_PKP3', 'ENSG00000184434_LRRC19', 'ENSG00000184454_NCMAP', 'ENSG00000184571_PIWIL3', 'ENSG00000184702_SEPT5', 'ENSG00000184908_CLCNKB', 'ENSG00000184923_NUTM2A', 'ENSG00000185070_FLRT2', 'ENSG00000185156_MFSD6L', 'ENSG00000185567_AHNAK2', 'ENSG00000185686_PRAME', 'ENSG00000186190_BPIFB3', 'ENSG00000186191_BPIFB4', 'ENSG00000186231_KLHL32', 'ENSG00000186431_FCAR', 'ENSG00000186715_MST1L', 'ENSG00000187116_LILRA5', 'ENSG00000187185_AC092118.1', 'ENSG00000187268_FAM9C', 'ENSG00000187554_TLR5', 'ENSG00000187867_PALM3', 'ENSG00000188153_COL4A5', 'ENSG00000188158_NHS', 'ENSG00000188163_FAM166A', 'ENSG00000188316_ENO4', 'ENSG00000188959_C9orf152', 'ENSG00000189013_KIR2DL4', 'ENSG00000189409_MMP23B', 'ENSG00000196092_PAX5', 'ENSG00000196260_SFTA2', 'ENSG00000197358_BNIP3P1', 'ENSG00000197446_CYP2F1', 'ENSG00000197540_GZMM', 'ENSG00000198049_AVPR1B', 'ENSG00000198134_AC007537.1', 'ENSG00000198156_NPIPB6', 'ENSG00000198221_AFDN-DT', 'ENSG00000198626_RYR2', 'ENSG00000198759_EGFL6', 'ENSG00000198822_GRM3', 'ENSG00000198963_RORB', 'ENSG00000199090_MIR326', 'ENSG00000199753_SNORD104', 'ENSG00000199787_RF00406', 'ENSG00000199872_RNU6-942P', 'ENSG00000200075_RF00402', 'ENSG00000200296_RNU1-83P', 'ENSG00000200683_RNU6-379P', 'ENSG00000201044_RNU6-268P', 'ENSG00000201343_RF00019', 'ENSG00000201564_RN7SKP50', 'ENSG00000201616_RNU1-91P', 'ENSG00000201737_RNU1-133P', 'ENSG00000202048_SNORD114-20', 'ENSG00000202415_RN7SKP269', 'ENSG00000203395_AC015969.1', 'ENSG00000203721_LINC00862', 'ENSG00000203727_SAMD5', 'ENSG00000203737_GPR52', 'ENSG00000203783_PRR9', 'ENSG00000203867_RBM20', 'ENSG00000203907_OOEP', 'ENSG00000203999_LINC01270', 'ENSG00000204010_IFIT1B', 'ENSG00000204044_SLC12A5-AS1', 'ENSG00000204091_TDRG1', 'ENSG00000204121_ECEL1P1', 'ENSG00000204165_CXorf65', 'ENSG00000204173_LRRC37A5P', 'ENSG00000204248_COL11A2', 'ENSG00000204424_LY6G6F', 'ENSG00000204539_CDSN', 'ENSG00000204583_LRCOL1', 'ENSG00000204677_FAM153C', 'ENSG00000204709_LINC01556', 'ENSG00000204711_C9orf135', 'ENSG00000204792_LINC01291', 'ENSG00000204850_AC011484.1', 'ENSG00000204851_PNMA8B', 'ENSG00000204909_SPINK9', 'ENSG00000205037_AC134312.1', 'ENSG00000205038_PKHD1L1', 'ENSG00000205089_CCNI2', 'ENSG00000205106_DKFZp779M0652', 'ENSG00000205364_MT1M', 'ENSG00000205502_C2CD4B', 'ENSG00000205746_AC126755.1', 'ENSG00000205856_C22orf42', 'ENSG00000206052_DOK6', 'ENSG00000206579_XKR4', 'ENSG00000206645_RF00019', 'ENSG00000206786_RNU6-701P', 'ENSG00000206846_RF00019', 'ENSG00000206848_RNU6-890P', 'ENSG00000207088_SNORA7B', 'ENSG00000207181_SNORA14B', 'ENSG00000207234_RNU6-125P', 'ENSG00000207326_RF00019', 'ENSG00000207359_RNU6-925P', 'ENSG00000211677_IGLC2', 'ENSG00000211699_TRGV3', 'ENSG00000211895_IGHA1', 'ENSG00000212385_RNU6-817P', 'ENSG00000212391_RF00554', 'ENSG00000212607_SNORA3B', 'ENSG00000212829_RPS26P3', 'ENSG00000213083_AC010731.1', 'ENSG00000213216_AC007066.1', 'ENSG00000213222_AC093724.1', 'ENSG00000213228_RPL12P38', 'ENSG00000213250_RBMS2P1', 'ENSG00000213272_RPL7AP9', 'ENSG00000213303_AC008481.1', 'ENSG00000213402_PTPRCAP', 'ENSG00000213471_TTLL13P', 'ENSG00000213588_ZBTB9', 'ENSG00000213609_RPL7AP50', 'ENSG00000213757_AC020898.1', 'ENSG00000213931_HBE1', 'ENSG00000213950_RPS10P2', 'ENSG00000213994_AL157395.1', 'ENSG00000214787_MS4A4E', 'ENSG00000214866_DCDC2C', 'ENSG00000214908_AL353678.1', 'ENSG00000214975_PPIAP29', 'ENSG00000215198_AL353795.1', 'ENSG00000215208_KRT18P60', 'ENSG00000215218_UBE2QL1', 'ENSG00000215297_AL354941.1', 'ENSG00000215464_AP000354.1', 'ENSG00000215483_LINC00598', 'ENSG00000215817_ZC3H11B', 'ENSG00000215861_AC245297.1', 'ENSG00000215910_C1orf167', 'ENSG00000216475_AL024474.1', 'ENSG00000217195_AL513475.1', 'ENSG00000217414_DDX18P3', 'ENSG00000217512_AL356776.1', 'ENSG00000218351_RPS3AP23', 'ENSG00000218418_AL591135.1', 'ENSG00000218749_AL033519.1', 'ENSG00000218766_AL450338.1', 'ENSG00000218792_HSPD1P16', 'ENSG00000219249_AMZ2P2', 'ENSG00000219395_HSPA8P15', 'ENSG00000219410_AC125494.1', 'ENSG00000219932_RPL12P8', 'ENSG00000220091_LAP3P1', 'ENSG00000220237_RPS24P12', 'ENSG00000220494_YAP1P1', 'ENSG00000221102_SNORA11B', 'ENSG00000221887_HMSD', 'ENSG00000222276_RNU2-33P', 'ENSG00000222370_SNORA36B', 'ENSG00000222421_RF00019', 'ENSG00000222431_RNU6-141P', 'ENSG00000223342_AL158817.1', 'ENSG00000223379_AL391987.3', 'ENSG00000223403_MEG9', 'ENSG00000223519_KIF28P', 'ENSG00000223576_AL355001.1', 'ENSG00000223668_EEF1A1P24', 'ENSG00000223741_PSMD4P1', 'ENSG00000223779_AC239800.1', 'ENSG00000223783_LINC01983', 'ENSG00000223784_LINP1', 'ENSG00000223855_HRAT92', 'ENSG00000223884_AC068481.1', 'ENSG00000223899_SEC13P1', 'ENSG00000224067_AL354877.1', 'ENSG00000224072_AL139811.1', 'ENSG00000224081_SLC44A3-AS1', 'ENSG00000224099_AC104823.1', 'ENSG00000224116_INHBA-AS1', 'ENSG00000224137_LINC01857', 'ENSG00000224155_AC073136.2', 'ENSG00000224321_RPL12P14', 'ENSG00000224402_OR6D1P', 'ENSG00000224479_AC104162.1', 'ENSG00000224599_BMS1P12', 'ENSG00000224689_ZNF812P', 'ENSG00000224848_AL589843.1', 'ENSG00000224908_TIMM8BP2', 'ENSG00000224957_LINC01266', 'ENSG00000224959_AC017002.1', 'ENSG00000224988_AL158207.1', 'ENSG00000224993_RPL29P12', 'ENSG00000225096_AL445250.1', 'ENSG00000225101_OR52K3P', 'ENSG00000225107_AC092484.1', 'ENSG00000225187_AC073283.1', 'ENSG00000225313_AL513327.1', 'ENSG00000225345_SNX18P3', 'ENSG00000225393_BX571846.1', 'ENSG00000225422_RBMS1P1', 'ENSG00000225423_TNPO1P1', 'ENSG00000225531_AL807761.2', 'ENSG00000225554_AL359764.1', 'ENSG00000225650_EIF2S2P5', 'ENSG00000225674_IPO7P2', 'ENSG00000225807_AC069281.1', 'ENSG00000226010_AL355852.1', 'ENSG00000226084_AC113935.1', 'ENSG00000226251_AL451060.1', 'ENSG00000226383_LINC01876', 'ENSG00000226491_FTOP1', 'ENSG00000226501_USF1P1', 'ENSG00000226545_AL357552.1', 'ENSG00000226564_FTH1P20', 'ENSG00000226617_RPL21P110', 'ENSG00000226647_AL365356.1', 'ENSG00000226800_CACTIN-AS1', 'ENSG00000226913_BSN-DT', 'ENSG00000226948_RPS4XP2', 'ENSG00000226970_AL450063.1', 'ENSG00000227006_AL136988.2', 'ENSG00000227051_C14orf132', 'ENSG00000227072_AL353706.1', 'ENSG00000227110_LMCD1-AS1', 'ENSG00000227192_AL023581.2', 'ENSG00000227198_C6orf47-AS1', 'ENSG00000227207_RPL31P12', 'ENSG00000227477_STK4-AS1', 'ENSG00000227541_SFR1P1', 'ENSG00000227590_ATP5MC1P5', 'ENSG00000227649_MTND6P32', 'ENSG00000227682_ATP5F1AP2', 'ENSG00000227740_AL513329.1', 'ENSG00000227742_CALR4P', 'ENSG00000228097_MTATP6P11', 'ENSG00000228140_AL031283.1', 'ENSG00000228175_GEMIN8P4', 'ENSG00000228212_OFD1P17', 'ENSG00000228232_GAPDHP1', 'ENSG00000228317_AL158070.1', 'ENSG00000228413_AC024937.1', 'ENSG00000228430_AL162726.3', 'ENSG00000228501_RPL15P18', 'ENSG00000228550_AC073583.1', 'ENSG00000228655_AC096558.1', 'ENSG00000228727_SAPCD1', 'ENSG00000228826_AL592494.1', 'ENSG00000228839_PIK3IP1-AS1', 'ENSG00000228863_AL121985.1', 'ENSG00000229066_AC093459.1', 'ENSG00000229150_CRYGEP', 'ENSG00000229154_KCNQ5-AS1', 'ENSG00000229163_NAP1L1P2', 'ENSG00000229236_TTTY10', 'ENSG00000229274_AL662860.1', 'ENSG00000229308_AC010737.1', 'ENSG00000229326_AC069154.1', 'ENSG00000229372_SZT2-AS1', 'ENSG00000229444_AL451062.1', 'ENSG00000229567_AL139421.1', 'ENSG00000229703_CR589904.1', 'ENSG00000229742_AC092809.1', 'ENSG00000229758_DYNLT3P2', 'ENSG00000229839_AC018462.1', 'ENSG00000229847_EMX2OS', 'ENSG00000229853_AL034418.1', 'ENSG00000229918_DOCK9-AS1', 'ENSG00000229953_AL590666.2', 'ENSG00000229992_HMGB3P9', 'ENSG00000230063_AL360091.2', 'ENSG00000230064_AL772161.1', 'ENSG00000230138_AC119428.2', 'ENSG00000230149_AL021707.3', 'ENSG00000230289_AL358781.2', 'ENSG00000230295_GTF2IP23', 'ENSG00000230479_AP000695.1', 'ENSG00000230508_RPL19P21', 'ENSG00000230519_HMGB1P49', 'ENSG00000230534_AL392046.1', 'ENSG00000230563_AL121757.1', 'ENSG00000230721_AL049597.1', 'ENSG00000230772_VN1R108P', 'ENSG00000230777_RPS29P5', 'ENSG00000230799_AC007279.1', 'ENSG00000230813_AL356583.3', 'ENSG00000230815_AL807757.1', 'ENSG00000230872_MFSD13B', 'ENSG00000230910_AL391807.1', 'ENSG00000230912_AL021707.4', 'ENSG00000230968_AC084149.2', 'ENSG00000230993_RPL12P15', 'ENSG00000231265_TRERNA1', 'ENSG00000231307_RPS3P2', 'ENSG00000231407_AL354732.1', 'ENSG00000231449_AC097359.1', 'ENSG00000231507_LINC01353', 'ENSG00000231531_HINT1P1', 'ENSG00000231548_OR55B1P', 'ENSG00000231731_AC010976.1', 'ENSG00000231742_LINC01273', 'ENSG00000231788_RPL31P50', 'ENSG00000231830_AC245140.1', 'ENSG00000231927_AC093734.1', 'ENSG00000231993_EP300-AS1', 'ENSG00000232027_AL671986.1', 'ENSG00000232028_AC007391.1', 'ENSG00000232065_LINC01063', 'ENSG00000232133_IMPDH1P10', 'ENSG00000232139_LINC00867', 'ENSG00000232273_FTH1P1', 'ENSG00000232333_RPS27AP2', 'ENSG00000232466_AL356133.1', 'ENSG00000232500_AP005273.1', 'ENSG00000232530_LIF-AS1', 'ENSG00000232568_RPL23AP35', 'ENSG00000232578_AC093311.1', 'ENSG00000232606_LINC01412', 'ENSG00000232654_FAM136BP', 'ENSG00000232656_IDI2-AS1', 'ENSG00000232719_AC007272.1', 'ENSG00000232803_SLCO4A1-AS1', 'ENSG00000232987_LINC01219', 'ENSG00000233025_CRYZP1', 'ENSG00000233093_LINC00892', 'ENSG00000233099_AC095030.1', 'ENSG00000233401_PRKAR1AP1', 'ENSG00000233427_AL009181.1', 'ENSG00000233540_DNM3-IT1', 'ENSG00000233674_AL451062.2', 'ENSG00000233825_AL391839.2', 'ENSG00000233862_AC016907.2', 'ENSG00000233994_GDI2P2', 'ENSG00000234026_AL157834.2', 'ENSG00000234106_SRP14P2', 'ENSG00000234145_NAP1L4P3', 'ENSG00000234174_AC016683.1', 'ENSG00000234271_Z98752.2', 'ENSG00000234425_AL138930.1', 'ENSG00000234488_AC096664.2', 'ENSG00000234630_AC245060.2', 'ENSG00000234645_YWHAEP5', 'ENSG00000234718_AC007161.1', 'ENSG00000234810_AL603840.1', 'ENSG00000235045_RPL7P8', 'ENSG00000235072_AC012074.1', 'ENSG00000235214_FAM83C-AS1', 'ENSG00000235288_AC099329.1', 'ENSG00000235376_RPEL1', 'ENSG00000235429_AC083875.1', 'ENSG00000235472_EIF4A1P7', 'ENSG00000235478_LINC01664', 'ENSG00000235531_MSC-AS1', 'ENSG00000235640_AC092646.2', 'ENSG00000235677_NPM1P26', 'ENSG00000235683_AC018442.1', 'ENSG00000235701_PCBP2P1', 'ENSG00000235740_PHACTR2-AS1', 'ENSG00000235774_AC023347.1', 'ENSG00000235802_HCFC1-AS1', 'ENSG00000235917_MTCO2P11', 'ENSG00000235958_UBOX5-AS1', 'ENSG00000236032_OR5H14', 'ENSG00000236180_AL445669.2', 'ENSG00000236254_MTND4P14', 'ENSG00000236283_AC019197.1', 'ENSG00000236290_EEF1GP7', 'ENSG00000236317_AC104333.2', 'ENSG00000236364_AL358115.1', 'ENSG00000236457_AC090617.1', 'ENSG00000236564_YWHAQP5', 'ENSG00000236671_PRKG1-AS1', 'ENSG00000236680_AL356000.1', 'ENSG00000236682_AC068282.1', 'ENSG00000236711_SMAD9-IT1', 'ENSG00000236806_RPL7AP15', 'ENSG00000236869_ZKSCAN7-AS1', 'ENSG00000236886_AC007563.2', 'ENSG00000236915_AL356270.1', 'ENSG00000236936_AL031005.1', 'ENSG00000237057_LINC02087', 'ENSG00000237101_AC092809.4', 'ENSG00000237276_ANO7L1', 'ENSG00000237317_AL022400.1', 'ENSG00000237387_AL022329.2', 'ENSG00000237618_BTBD7P2', 'ENSG00000237685_AL139039.3', 'ENSG00000237757_EEF1A1P30', 'ENSG00000237766_GGTA2P', 'ENSG00000237798_AC010894.4', 'ENSG00000238015_AC104837.2', 'ENSG00000238133_MAP3K20-AS1', 'ENSG00000238259_AC067940.1', 'ENSG00000238324_RN7SKP198', 'ENSG00000238358_AC004969.1', 'ENSG00000239219_AC008040.1', 'ENSG00000239316_RN7SL11P', 'ENSG00000239474_KLHL41', 'ENSG00000239527_RPS23P7', 'ENSG00000239642_MEIKIN', 'ENSG00000239650_GUSBP4', 'ENSG00000239686_AL158801.1', 'ENSG00000239701_AC006512.1', 'ENSG00000239705_AL354710.2', 'ENSG00000239797_RPL21P39', 'ENSG00000239830_RPS4XP22', 'ENSG00000239930_AP001625.3', 'ENSG00000240086_AC092969.1', 'ENSG00000240087_RPSAP12', 'ENSG00000240183_RN7SL297P', 'ENSG00000240219_AL512306.2', 'ENSG00000240498_CDKN2B-AS1', 'ENSG00000240809_AC026877.1', 'ENSG00000240993_RN7SL459P', 'ENSG00000241111_PRICKLE2-AS1', 'ENSG00000241135_LINC00881', 'ENSG00000241319_SETP6', 'ENSG00000241570_PAQR9-AS1', 'ENSG00000241631_RN7SL316P', 'ENSG00000241932_AC092324.1', 'ENSG00000241933_DENND6A-DT', 'ENSG00000242060_RPS3AP49', 'ENSG00000242107_LINC01100', 'ENSG00000242175_RN7SL127P', 'ENSG00000242431_AC107398.1', 'ENSG00000242551_POU5F1P6', 'ENSG00000242571_RPL21P11', 'ENSG00000242641_LINC00971', 'ENSG00000242747_AC090515.1', 'ENSG00000242992_FTH1P4', 'ENSG00000243055_GK-AS1', 'ENSG00000243498_UBA52P5', 'ENSG00000243592_RPL17P22', 'ENSG00000243709_LEFTY1', 'ENSG00000243830_AC092865.1', 'ENSG00000243836_WDR86-AS1', 'ENSG00000243961_PARAL1', 'ENSG00000244021_AC093591.1', 'ENSG00000244097_RPS4XP17', 'ENSG00000244151_AC010973.2', 'ENSG00000244183_PPIAP71', 'ENSG00000244242_IFITM10', 'ENSG00000244245_AC133134.1', 'ENSG00000244251_AC013356.1', 'ENSG00000244355_LY6G6D', 'ENSG00000244357_RN7SL145P', 'ENSG00000244476_ERVFRD-1', 'ENSG00000244482_LILRA6', 'ENSG00000244585_RPL12P33', 'ENSG00000244618_RN7SL334P', 'ENSG00000244703_CD46P1', 'ENSG00000245261_AL133375.1', 'ENSG00000245482_AC046130.1', 'ENSG00000246363_LINC02458', 'ENSG00000246863_AC012377.1', 'ENSG00000247199_AC091948.1', 'ENSG00000248121_SMURF2P1', 'ENSG00000248155_CR545473.1', 'ENSG00000248223_AC026785.2', 'ENSG00000248485_PCP4L1', 'ENSG00000248690_HAS2-AS1', 'ENSG00000248884_AC010280.2', 'ENSG00000248936_AC027607.1', 'ENSG00000249140_PRDX2P3', 'ENSG00000249363_AC011411.1', 'ENSG00000249381_LINC00500', 'ENSG00000249456_AL731577.2', 'ENSG00000249492_AC114956.3', 'ENSG00000249574_AC226118.1', 'ENSG00000249614_LINC02503', 'ENSG00000249691_AC026117.1', 'ENSG00000249695_AC026369.1', 'ENSG00000249803_AC112178.1', 'ENSG00000249825_CTD-2201I18.1', 'ENSG00000249848_AC112673.1', 'ENSG00000249850_KRT18P31', 'ENSG00000249884_RNF103-CHMP3', 'ENSG00000249978_TRGV7', 'ENSG00000250130_AC090519.1', 'ENSG00000250148_KRT8P31', 'ENSG00000250332_AC010460.3', 'ENSG00000250334_LINC00989', 'ENSG00000250539_KRT8P33', 'ENSG00000250548_LINC01303', 'ENSG00000250608_AC010210.1', 'ENSG00000250635_CXXC5-AS1', 'ENSG00000250645_AC010442.2', 'ENSG00000250733_C8orf17', 'ENSG00000250853_RNF138P1', 'ENSG00000250902_SMAD1-AS1', 'ENSG00000250950_AC093752.2', 'ENSG00000250982_GAPDHP35', 'ENSG00000251129_LINC02506', 'ENSG00000251152_AC025539.1', 'ENSG00000251250_AC091951.3', 'ENSG00000251288_AC018797.3', 'ENSG00000251468_AC135352.1', 'ENSG00000251537_AC005324.3', 'ENSG00000251538_LINC02201', 'ENSG00000251584_AC096751.2', 'ENSG00000251676_SNHG27', 'ENSG00000251916_RNU1-61P', 'ENSG00000252759_RF00019', 'ENSG00000253256_AC134043.1', 'ENSG00000253305_PCDHGB6', 'ENSG00000253394_LINC00534', 'ENSG00000253490_LINC02099', 'ENSG00000253537_PCDHGA7', 'ENSG00000253629_AP000426.1', 'ENSG00000253651_SOD1P3', 'ENSG00000253730_AC015909.2', 'ENSG00000253734_LINC01289', 'ENSG00000253767_PCDHGA8', 'ENSG00000253853_AC246817.1', 'ENSG00000253873_PCDHGA11', 'ENSG00000254028_AC083843.1', 'ENSG00000254048_AC105150.1', 'ENSG00000254054_AC087273.2', 'ENSG00000254122_PCDHGB7', 'ENSG00000254248_AC068189.1', 'ENSG00000254680_AC079329.1', 'ENSG00000254708_AL139174.1', 'ENSG00000254780_AC023232.1', 'ENSG00000254810_AP001189.3', 'ENSG00000254812_AC067930.3', 'ENSG00000254842_LINC02551', 'ENSG00000254846_AL355075.1', 'ENSG00000254862_AC100771.2', 'ENSG00000254897_AP003035.1', 'ENSG00000255002_LINC02324', 'ENSG00000255074_AC018523.1', 'ENSG00000255102_AP005436.1', 'ENSG00000255156_RNY1P9', 'ENSG00000255158_AC131934.1', 'ENSG00000255222_SETP17', 'ENSG00000255256_AL136146.2', 'ENSG00000255367_AC127526.2', 'ENSG00000255418_AC090092.1', 'ENSG00000255443_CD44-AS1', 'ENSG00000255446_AP003064.2', 'ENSG00000255479_AP001189.6', 'ENSG00000255487_AC087362.2', 'ENSG00000255867_DENND5B-AS1', 'ENSG00000255871_AC007529.1', 'ENSG00000256029_SNHG28', 'ENSG00000256571_AC079866.2', 'ENSG00000256588_AC027544.2', 'ENSG00000256712_AC134349.1', 'ENSG00000256746_AC018410.1', 'ENSG00000256813_AP000777.3', 'ENSG00000256967_AC018653.3', 'ENSG00000256968_SNRPEP2', 'ENSG00000257074_RPL29P33', 'ENSG00000257120_AL356756.1', 'ENSG00000257146_AC079905.2', 'ENSG00000257195_HNRNPA1P50', 'ENSG00000257327_AC012555.1', 'ENSG00000257345_LINC02413', 'ENSG00000257379_AC023509.1', 'ENSG00000257386_AC025257.1', 'ENSG00000257431_AC089998.1', 'ENSG00000257715_AC007298.1', 'ENSG00000257838_OTOAP1', 'ENSG00000257987_TEX49', 'ENSG00000258084_AC128707.1', 'ENSG00000258090_AC093014.1', 'ENSG00000258177_AC008149.1', 'ENSG00000258357_AC023161.2', 'ENSG00000258410_AC087386.1', 'ENSG00000258498_DIO3OS', 'ENSG00000258504_AL157871.1', 'ENSG00000258512_LINC00239', 'ENSG00000258867_LINC01146', 'ENSG00000258886_HIGD1AP17', 'ENSG00000259032_ENSAP2', 'ENSG00000259100_AL157791.1', 'ENSG00000259294_AC005096.1', 'ENSG00000259327_AC023906.3', 'ENSG00000259345_AC013652.1', 'ENSG00000259377_AC026770.1', 'ENSG00000259380_AC087473.1', 'ENSG00000259442_AC105339.3', 'ENSG00000259461_ANP32BP3', 'ENSG00000259556_AC090971.3', 'ENSG00000259569_AC013489.2', 'ENSG00000259617_AC020661.3', 'ENSG00000259684_AC084756.1', 'ENSG00000259719_LINC02284', 'ENSG00000259954_IL21R-AS1', 'ENSG00000259986_AC103876.1', 'ENSG00000260135_MMP2-AS1', 'ENSG00000260206_AC105020.2', 'ENSG00000260235_AC105020.3', 'ENSG00000260269_AC105036.3', 'ENSG00000260394_Z92544.1', 'ENSG00000260425_AL031709.1', 'ENSG00000260447_AC009065.3', 'ENSG00000260615_RPL23AP97', 'ENSG00000260871_AC093510.2', 'ENSG00000260877_AP005233.2', 'ENSG00000260979_AC022167.3', 'ENSG00000261051_AC107021.2', 'ENSG00000261113_AC009034.1', 'ENSG00000261168_AL592424.1', 'ENSG00000261253_AC137932.2', 'ENSG00000261269_AC093278.2', 'ENSG00000261552_AC109460.4', 'ENSG00000261572_AC097639.1', 'ENSG00000261602_AC092115.2', 'ENSG00000261630_AC007496.2', 'ENSG00000261644_AC007728.2', 'ENSG00000261734_AC116096.1', 'ENSG00000261773_AC244090.2', 'ENSG00000261837_AC046158.2', 'ENSG00000261838_AC092718.6', 'ENSG00000261888_AC144831.1', 'ENSG00000262061_AC129507.1', 'ENSG00000262097_LINC02185', 'ENSG00000262372_CR936218.1', 'ENSG00000262406_MMP12', 'ENSG00000262580_AC087741.1', 'ENSG00000262772_LINC01977', 'ENSG00000262833_AC016245.1', 'ENSG00000263006_ROCK1P1', 'ENSG00000263011_AC108134.4', 'ENSG00000263155_MYZAP', 'ENSG00000263393_AC011825.2', 'ENSG00000263426_RN7SL471P', 'ENSG00000263503_MAPK8IP1P2', 'ENSG00000263595_RN7SL823P', 'ENSG00000263878_DLGAP1-AS4', 'ENSG00000263940_RN7SL275P', 'ENSG00000264019_AC018521.2', 'ENSG00000264031_ABHD15-AS1', 'ENSG00000264044_AC005726.2', 'ENSG00000264070_DND1P1', 'ENSG00000264188_AC106037.1', 'ENSG00000264269_AC016866.1', 'ENSG00000264339_AP001020.1', 'ENSG00000264434_AC110603.1', 'ENSG00000264714_KIAA0895LP1', 'ENSG00000265010_AC087301.1', 'ENSG00000265073_AC010761.2', 'ENSG00000265107_GJA5', 'ENSG00000265179_AP000894.2', 'ENSG00000265218_AC103810.2', 'ENSG00000265334_AC130324.2', 'ENSG00000265439_RN7SL811P', 'ENSG00000265531_FCGR1CP', 'ENSG00000265845_AC024267.4', 'ENSG00000265907_AP000919.2', 'ENSG00000265942_RN7SL577P', 'ENSG00000266256_LINC00683', 'ENSG00000266456_AP001178.3', 'ENSG00000266733_TBC1D29', 'ENSG00000266835_GAPLINC', 'ENSG00000266844_AC093330.1', 'ENSG00000266903_AC243964.2', 'ENSG00000266944_AC005262.1', 'ENSG00000266946_MRPL37P1', 'ENSG00000266947_AC022916.1', 'ENSG00000267034_AC010980.2', 'ENSG00000267044_AC005757.1', 'ENSG00000267147_LINC01842', 'ENSG00000267175_AC105094.2', 'ENSG00000267191_AC006213.3', 'ENSG00000267275_AC020911.2', 'ENSG00000267288_AC138150.2', 'ENSG00000267313_KC6', 'ENSG00000267316_AC090409.2', 'ENSG00000267323_SLC25A1P5', 'ENSG00000267345_AC010632.1', 'ENSG00000267387_AC020931.1', 'ENSG00000267395_DM1-AS', 'ENSG00000267429_AC006116.6', 'ENSG00000267452_LINC02073', 'ENSG00000267491_AC100788.1', 'ENSG00000267529_AP005131.4', 'ENSG00000267554_AC015911.8', 'ENSG00000267601_AC022966.1', 'ENSG00000267638_AC023855.1', 'ENSG00000267665_AC021683.3', 'ENSG00000267681_AC135721.1', 'ENSG00000267703_AC020917.2', 'ENSG00000267731_AC005332.2', 'ENSG00000267733_AP005264.5', 'ENSG00000267750_RUNDC3A-AS1', 'ENSG00000267890_AC010624.2', 'ENSG00000267898_AC026803.2', 'ENSG00000267927_AC010320.1', 'ENSG00000268070_AC006539.2', 'ENSG00000268355_AC243960.3', 'ENSG00000268416_AC010329.1', 'ENSG00000268520_AC008750.5', 'ENSG00000268636_AC011495.2', 'ENSG00000268696_ZNF723', 'ENSG00000268777_AC020914.1', 'ENSG00000268849_SIGLEC22P', 'ENSG00000268903_AL627309.6', 'ENSG00000268983_AC005253.2', 'ENSG00000269019_HOMER3-AS1', 'ENSG00000269067_ZNF728', 'ENSG00000269103_RF00017', 'ENSG00000269274_AC078899.4', 'ENSG00000269288_AC092070.3', 'ENSG00000269352_PTOV1-AS2', 'ENSG00000269400_AC008734.2', 'ENSG00000269506_AC110792.2', 'ENSG00000269653_AC011479.3', 'ENSG00000269881_AC004754.1', 'ENSG00000269926_DDIT4-AS1', 'ENSG00000270048_AC068790.4', 'ENSG00000270050_AL035427.1', 'ENSG00000270503_YTHDF2P1', 'ENSG00000270706_PRMT1P1', 'ENSG00000270765_GAS2L2', 'ENSG00000270882_HIST2H4A', 'ENSG00000270906_MTND4P35', 'ENSG00000271013_LRRC37A9P', 'ENSG00000271129_AC009027.1', 'ENSG00000271259_AC010201.1', 'ENSG00000271524_BNIP3P17', 'ENSG00000271543_AC021443.1', 'ENSG00000271743_AF287957.1', 'ENSG00000271792_AC008667.4', 'ENSG00000271868_AC114810.1', 'ENSG00000271973_AC141002.1', 'ENSG00000271984_AL008726.1', 'ENSG00000271996_AC019080.4', 'ENSG00000272070_AC005618.1', 'ENSG00000272138_LINC01607', 'ENSG00000272150_NBPF25P', 'ENSG00000272265_AC034236.3', 'ENSG00000272279_AL512329.2', 'ENSG00000272473_AC006273.1', 'ENSG00000272510_AL121992.3', 'ENSG00000272582_AL031587.3', 'ENSG00000272695_GAS6-DT', 'ENSG00000272732_AC004982.1', 'ENSG00000272770_AC005696.2', 'ENSG00000272788_AP000864.1', 'ENSG00000272824_AC245100.7', 'ENSG00000272825_AL844908.1', 'ENSG00000272848_AL135910.1', 'ENSG00000272916_AC022400.6', 'ENSG00000273133_AC116651.1', 'ENSG00000273177_AC092954.2', 'ENSG00000273212_AC000068.2', 'ENSG00000273218_AC005776.2', 'ENSG00000273245_AC092653.1', 'ENSG00000273274_ZBTB8B', 'ENSG00000273312_AL121749.1', 'ENSG00000273325_AL008723.3', 'ENSG00000273369_AC096586.2', 'ENSG00000273474_AL157392.4', 'ENSG00000273599_AL731571.1', 'ENSG00000273724_AC106782.5', 'ENSG00000273870_AL138721.1', 'ENSG00000273920_AC103858.2', 'ENSG00000274023_AL360169.2', 'ENSG00000274029_AC069209.1', 'ENSG00000274114_ALOX15P1', 'ENSG00000274124_AC074029.3', 'ENSG00000274139_AC090164.2', 'ENSG00000274281_AC022929.2', 'ENSG00000274308_AC244093.1', 'ENSG00000274373_AC148476.1', 'ENSG00000274386_TMEM269', 'ENSG00000274403_AC090510.2', 'ENSG00000274570_SPDYE10P', 'ENSG00000274670_AC137590.2', 'ENSG00000274723_AC079906.1', 'ENSG00000274742_RF00017', 'ENSG00000274798_AC025166.1', 'ENSG00000274911_AL627230.2', 'ENSG00000275106_AC025594.2', 'ENSG00000275197_AC092794.2', 'ENSG00000275302_CCL4', 'ENSG00000275348_AC096861.1', 'ENSG00000275367_AC092111.1', 'ENSG00000275489_C17orf98', 'ENSG00000275527_AC100835.2', 'ENSG00000275995_AC109809.1', 'ENSG00000276070_CCL4L2', 'ENSG00000276255_AL136379.1', 'ENSG00000276282_AC022960.2', 'ENSG00000276547_PCDHGB5', 'ENSG00000276704_AL442067.2', 'ENSG00000276952_AL121772.3', 'ENSG00000276984_AL023881.1', 'ENSG00000276997_AL513314.2', 'ENSG00000277117_FP565260.3', 'ENSG00000277152_AC110048.2', 'ENSG00000277186_AC131212.1', 'ENSG00000277229_AC084781.1', 'ENSG00000277496_AL357033.4', 'ENSG00000277504_AC010536.3', 'ENSG00000277531_PNMA8C', 'ENSG00000278041_AL133325.3', 'ENSG00000278344_AC063943.1', 'ENSG00000278467_AC138393.3', 'ENSG00000278513_AC091046.2', 'ENSG00000278621_AC037198.2', 'ENSG00000278713_AC120114.2', 'ENSG00000278716_AC133540.1', 'ENSG00000278746_RN7SL660P', 'ENSG00000278774_RF00004', 'ENSG00000279091_AC026523.2', 'ENSG00000279130_AC091925.1', 'ENSG00000279141_LINC01451', 'ENSG00000279161_AC093503.3', 'ENSG00000279187_AC027601.5', 'ENSG00000279263_OR2L8', 'ENSG00000279315_AL158212.4', 'ENSG00000279319_AC105074.1', 'ENSG00000279332_AC090772.4', 'ENSG00000279339_AC100788.2', 'ENSG00000279365_AP000695.3', 'ENSG00000279378_AC009159.4', 'ENSG00000279384_AC080188.2', 'ENSG00000279404_AC008739.5', 'ENSG00000279417_AC019322.4', 'ENSG00000279444_AC135584.1', 'ENSG00000279486_OR2AG1', 'ENSG00000279530_AC092881.1', 'ENSG00000279590_AC005786.4', 'ENSG00000279619_AC020907.5', 'ENSG00000279633_AL137918.1', 'ENSG00000279636_LINC00216', 'ENSG00000279672_AP006621.5', 'ENSG00000279690_AP000280.1', 'ENSG00000279727_LINC02033', 'ENSG00000279861_AC073548.1', 'ENSG00000279913_AP001962.1', 'ENSG00000279970_AC023024.2', 'ENSG00000280055_TMEM75', 'ENSG00000280057_AL022069.2', 'ENSG00000280135_AL096816.1', 'ENSG00000280310_AC092437.1', 'ENSG00000280422_AC115284.2', 'ENSG00000280432_AP000962.2', 'ENSG00000280693_SH3PXD2A-AS1', 'ENSG00000281490_CICP14', 'ENSG00000281530_AC004461.2', 'ENSG00000281571_AC241585.2', 'ENSG00000282772_AL358790.1', 'ENSG00000282989_AP001206.1', 'ENSG00000282996_AC022021.1', 'ENSG00000283023_FRG1GP', 'ENSG00000283031_AC009242.1', 'ENSG00000283097_AL159152.1', 'ENSG00000283141_AL157832.3', 'ENSG00000283209_AC106858.1', 'ENSG00000283538_AC005972.3', 'ENSG00000284240_AC099062.1', 'ENSG00000284512_AC092718.8', 'ENSG00000284657_AL031432.5', 'ENSG00000284664_AL161756.3', 'ENSG00000284931_AC104389.5', 'ENSG00000285016_AC017002.6', 'ENSG00000285117_AC068724.4', 'ENSG00000285162_AC004593.3', 'ENSG00000285210_AL136382.1', 'ENSG00000285215_AC241377.4', 'ENSG00000285292_AC021097.2', 'ENSG00000285498_AC104389.6', 'ENSG00000285534_AL163541.1', 'ENSG00000285577_AC019127.1', 'ENSG00000285611_AC007132.1', 'ENSG00000285629_AL031847.2', 'ENSG00000285641_AL358472.6', 'ENSG00000285649_AL357079.2', 'ENSG00000285650_AL157827.2', 'ENSG00000285662_AL731733.1', 'ENSG00000285672_AL160396.2', 'ENSG00000285763_AL358777.1', 'ENSG00000285865_AC010285.3', 'ENSG00000285879_AC018628.2']
print('Constant cols:', len(constant_cols))

important_cols = ['ENSG00000114013_CD86', 'ENSG00000120217_CD274', 'ENSG00000196776_CD47', 'ENSG00000117091_CD48', 'ENSG00000101017_CD40', 'ENSG00000102245_CD40LG', 'ENSG00000169442_CD52', 'ENSG00000117528_ABCD3', 'ENSG00000168014_C2CD3', 'ENSG00000167851_CD300A', 'ENSG00000167850_CD300C', 'ENSG00000186407_CD300E', 'ENSG00000178789_CD300LB', 'ENSG00000186074_CD300LF', 'ENSG00000241399_CD302', 'ENSG00000167775_CD320', 'ENSG00000105383_CD33', 'ENSG00000174059_CD34', 'ENSG00000135218_CD36', 'ENSG00000104894_CD37', 'ENSG00000004468_CD38', 'ENSG00000167286_CD3D', 'ENSG00000198851_CD3E', 'ENSG00000117877_CD3EAP', 'ENSG00000074696_HACD3', 'ENSG00000015676_NUDCD3', 'ENSG00000161714_PLCD3', 'ENSG00000132300_PTCD3', 'ENSG00000082014_SMARCD3', 'ENSG00000121594_CD80', 'ENSG00000110651_CD81', 'ENSG00000238184_CD81-AS1', 'ENSG00000085117_CD82', 'ENSG00000112149_CD83', 'ENSG00000066294_CD84', 'ENSG00000114013_CD86', 'ENSG00000172116_CD8B', 'ENSG00000254126_CD8B2', 'ENSG00000177455_CD19', 'ENSG00000105383_CD33', 'ENSG00000173762_CD7', 'ENSG00000125726_CD70', 'ENSG00000137101_CD72', 'ENSG00000019582_CD74', 'ENSG00000105369_CD79A', 'ENSG00000007312_CD79B', 'ENSG00000090470_PDCD7', 'ENSG00000119688_ABCD4', 'ENSG00000010610_CD4', 'ENSG00000101017_CD40', 'ENSG00000102245_CD40LG', 'ENSG00000026508_CD44', 'ENSG00000117335_CD46', 'ENSG00000196776_CD47', 'ENSG00000117091_CD48', 'ENSG00000188921_HACD4', 'ENSG00000150593_PDCD4', 'ENSG00000203497_PDCD4-AS1', 'ENSG00000115556_PLCD4', 'ENSG00000026508_CD44', 'ENSG00000170458_CD14', 'ENSG00000117281_CD160', 'ENSG00000177575_CD163', 'ENSG00000135535_CD164', 'ENSG00000091972_CD200', 'ENSG00000163606_CD200R1', 'ENSG00000206531_CD200R1L', 'ENSG00000182685_BRICD5', 'ENSG00000111731_C2CD5', 'ENSG00000169442_CD52', 'ENSG00000143119_CD53', 'ENSG00000196352_CD55', 'ENSG00000116815_CD58', 'ENSG00000085063_CD59', 'ENSG00000105185_PDCD5', 'ENSG00000255909_PDCD5P1', 'ENSG00000145284_SCD5', 'ENSG00000167775_CD320', 'ENSG00000110848_CD69', 'ENSG00000139187_KLRG1', 'ENSG00000139193_CD27', 'ENSG00000215039_CD27-AS1', 'ENSG00000120217_CD274', 'ENSG00000103855_CD276', 'ENSG00000204287_HLA-DRA', 'ENSG00000196126_HLA-DRB1', 'ENSG00000198502_HLA-DRB5', 'ENSG00000229391_HLA-DRB6', 'ENSG00000116815_CD58', 'ENSG00000168329_CX3CR1', 'ENSG00000272398_CD24', 'ENSG00000122223_CD244', 'ENSG00000198821_CD247', 'ENSG00000122223_CD244', 'ENSG00000177575_CD163', 'ENSG00000112149_CD83', 'ENSG00000185963_BICD2', 'ENSG00000157617_C2CD2', 'ENSG00000172375_C2CD2L', 'ENSG00000116824_CD2', 'ENSG00000091972_CD200', 'ENSG00000163606_CD200R1', 'ENSG00000206531_CD200R1L', 'ENSG00000012124_CD22', 'ENSG00000150637_CD226', 'ENSG00000272398_CD24', 'ENSG00000122223_CD244', 'ENSG00000198821_CD247', 'ENSG00000139193_CD27', 'ENSG00000215039_CD27-AS1', 'ENSG00000120217_CD274', 'ENSG00000103855_CD276', 'ENSG00000198087_CD2AP', 'ENSG00000169217_CD2BP2', 'ENSG00000144554_FANCD2', 'ENSG00000206527_HACD2', 'ENSG00000170584_NUDCD2', 'ENSG00000071994_PDCD2', 'ENSG00000126249_PDCD2L', 'ENSG00000049883_PTCD2', 'ENSG00000186193_SAPCD2', 'ENSG00000108604_SMARCD2', 'ENSG00000185561_TLCD2', 'ENSG00000075035_WSCD2', 'ENSG00000150637_CD226', 'ENSG00000110651_CD81', 'ENSG00000238184_CD81-AS1', 'ENSG00000134061_CD180', 'ENSG00000004468_CD38', 'ENSG00000012124_CD22', 'ENSG00000150637_CD226', 'ENSG00000135404_CD63', 'ENSG00000135218_CD36', 'ENSG00000137101_CD72', 'ENSG00000125810_CD93', 'ENSG00000010278_CD9', 'ENSG00000125810_CD93', 'ENSG00000153283_CD96', 'ENSG00000002586_CD99', 'ENSG00000102181_CD99L2', 'ENSG00000223773_CD99P1', 'ENSG00000204592_HLA-E', 'ENSG00000085117_CD82', 'ENSG00000134256_CD101']
print('Important cols:', len(important_cols))

Constant cols: 1194
Important cols: 144


In [14]:
cite_keys = list(pd.read_hdf('data/train_cite_inputs.h5', start=0, stop=100).keys())

important_idxs = []
other_idxs = []
for i, s in enumerate(cite_keys):
    if s in important_cols:
        important_idxs.append(i)
    elif s not in constant_cols:
        other_idxs.append(i)

ENSG00000114013_CD86
ENSG00000114013_CD86


In [31]:
class PredLoss():
        def __init__(self, model, indices_to_use):
            self.model = model
            self.idxs = torch.tensor(indices_to_use, requires_grad=False)
        
        def loss(self, x, day, y):
            rna = x[:, self.idxs]
            protein_hat = self.model(rna)
            loss = F.mse_loss(protein_hat, y)
            return loss

        def error(self, x, day, y):
            rna = x[:, self.idxs]
            protein_hat = self.model(rna)
            loss = F.mse_loss(protein_hat, y)
            return loss.item()

In [34]:
model = models.LinearCoder([len(other_idxs), 768, 140], dropout=0.05, input_2d=False)
models.count_parameters(model)

batch_size = 128

train_dataloader = H5Dataset('train', 'cite').get_dataloader(batch_size)
val_dataloader = H5Dataset('val', 'cite').get_dataloader(batch_size)

l = PredLoss(model, other_idxs)

trainer = Trainer(model, 'cite_other', l.loss, l.error, train_dataloader, val_dataloader, 0.02, 2, 0.5, 0.001)
trainer.train(10, 1, 10000, 2)

Using cpu for training
Adjusting learning rate of group 0 to 2.0000e-02.
Training the following model for 10 epochs:

LinearCoder(
  (blocks): Sequential(
    (0): LinearBlock(
      (in_linear): Linear(in_features=20746, out_features=768, bias=True)
      (out_linear): Linear(in_features=768, out_features=768, bias=True)
      (activation): ReLU()
      (out_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.05, inplace=False)
    )
    (1): LinearBlock(
      (in_linear): Linear(in_features=768, out_features=140, bias=True)
      (out_linear): Linear(in_features=140, out_features=140, bias=True)
      (activation): ReLU()
      (out_norm): LayerNorm((140,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.05, inplace=False)
    )
  )
) with 16653504 parameters

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 0  -------------------
------------------------------------------------

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:32<00:00,  4.77it/s]


Adjusting learning rate of group 0 to 2.0000e-02.
avg batch training loss for epoch 0: 4.633674

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 0  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:12<00:00,  6.79it/s]


avg validation error for epoch 0: 3.662022
Saved checkpoint for epoch num 0

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 1  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:24<00:00,  5.26it/s]


Adjusting learning rate of group 0 to 1.0000e-02.
avg batch training loss for epoch 1: 3.319684

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 1  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.44it/s]


avg validation error for epoch 1: 3.155081
Saved checkpoint for epoch num 1

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 2  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:21<00:00,  5.42it/s]


Adjusting learning rate of group 0 to 1.0000e-02.
avg batch training loss for epoch 2: 2.971258

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 2  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:10<00:00,  7.56it/s]


avg validation error for epoch 2: 2.818278
Saved checkpoint for epoch num 2

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 3  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:25<00:00,  5.16it/s]


Adjusting learning rate of group 0 to 5.0000e-03.
avg batch training loss for epoch 3: 2.713511

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 3  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.15it/s]


avg validation error for epoch 3: 2.777912
Saved checkpoint for epoch num 3

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 4  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:25<00:00,  5.18it/s]


Adjusting learning rate of group 0 to 5.0000e-03.
avg batch training loss for epoch 4: 2.584143

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 4  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.28it/s]


avg validation error for epoch 4: 2.734555
Saved checkpoint for epoch num 4

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 5  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:26<00:00,  5.14it/s]


Adjusting learning rate of group 0 to 2.5000e-03.
avg batch training loss for epoch 5: 2.527406

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 5  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.12it/s]


avg validation error for epoch 5: 2.69374
Saved checkpoint for epoch num 5

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 6  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:28<00:00,  5.03it/s]


Adjusting learning rate of group 0 to 2.5000e-03.
avg batch training loss for epoch 6: 2.452208

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 6  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.23it/s]


avg validation error for epoch 6: 2.691775
Saved checkpoint for epoch num 6

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 7  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:27<00:00,  5.08it/s]


Adjusting learning rate of group 0 to 1.2500e-03.
avg batch training loss for epoch 7: 2.423248

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 7  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.29it/s]


avg validation error for epoch 7: 2.699357
Patience 1 hit

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 8  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:24<00:00,  5.27it/s]


Adjusting learning rate of group 0 to 1.2500e-03.
avg batch training loss for epoch 8: 2.384093

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 8  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.49it/s]


avg validation error for epoch 8: 2.703033
Patience 2 hit

-------------------------------------------------------------
------------------  TRAIN - EPOCH NUM 9  -------------------
-------------------------------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 443/443 [01:23<00:00,  5.31it/s]


Adjusting learning rate of group 0 to 6.2500e-04.
avg batch training loss for epoch 9: 2.368587

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 9  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.48it/s]


avg validation error for epoch 9: 2.695218
Patience 3 hit

-------------------------------------------------------------
-------------------  VAL - EPOCH NUM 10  -------------------
-------------------------------------------------------------


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:11<00:00,  7.48it/s]

avg validation error for epoch 10: 2.694912

Done :)


LinearCoder(
  (blocks): Sequential(
    (0): LinearBlock(
      (in_linear): Linear(in_features=20746, out_features=768, bias=True)
      (out_linear): Linear(in_features=768, out_features=768, bias=True)
      (activation): ReLU()
      (out_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.05, inplace=False)
    )
    (1): LinearBlock(
      (in_linear): Linear(in_features=768, out_features=140, bias=True)
      (out_linear): Linear(in_features=140, out_features=140, bias=True)
      (activation): ReLU()
      (out_norm): LayerNorm((140,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.05, inplace=False)
    )
  )
)

In [36]:
model.eval()
test_dataloader = H5Dataset('test', 'cite').get_dataloader(1)
for (x, day), y in test_dataloader:
    other = x[:, other_idxs]
    out = model(other)
    print(out[0, :20])
    print(y[0, :20])

tensor([0.6792, 0.2786, 0.3904, 4.5201, 4.4369, 4.7899, 8.7721, 0.1456, 0.2409,
        0.1171, 0.0730, 0.2305, 0.2345, 0.2323, 7.9835, 0.6232, 4.5302, 3.3223,
        0.5985, 0.2030], grad_fn=<SliceBackward0>)
tensor([-0.3444, -0.1960,  1.8092,  6.2503,  6.3128,  8.0135, 13.5457,  0.6012,
         0.2539,  1.4490, -0.8003,  1.4287, -0.0680, -0.5787,  9.4076,  2.8544,
         6.7148,  6.4064,  1.7061, -0.2298])
tensor([ 0.2285,  0.2663,  0.6972,  5.8480,  5.0076,  8.3753,  2.7331,  0.1846,
         0.6233,  0.2373,  0.0303,  0.2903,  0.3463,  0.3478, 11.4621,  0.8507,
         6.5284,  1.2578,  1.2962,  0.6134], grad_fn=<SliceBackward0>)
tensor([ 8.0132e-01, -1.4574e+00,  1.5539e+00,  6.4116e+00,  5.8380e+00,
         8.2226e+00,  7.5581e-01,  7.2721e-03,  4.6156e-01,  8.3946e-02,
         3.9896e-01,  1.1448e+00,  4.6064e-01, -7.1466e-01,  1.0280e+01,
         2.5343e+00,  5.7520e+00,  4.1914e-01,  2.6344e+00, -3.1250e-01])
tensor([ 0.3580,  0.6847,  1.3181,  7.2344,  7.2635,  5.4618

tensor([0.1402, 0.2847, 0.5930, 4.4387, 5.0382, 6.3673, 0.7862, 0.1937, 0.4765,
        0.5590, 0.0841, 0.2948, 0.2853, 0.2953, 5.3308, 0.3801, 5.9037, 1.3775,
        2.6079, 0.5800], grad_fn=<SliceBackward0>)
tensor([-0.2701,  0.4727,  1.6454,  6.3328,  6.1874,  2.9267,  0.7325,  1.6824,
        -0.9068, -0.2602, -0.0193, -0.1731,  0.3118,  0.3526,  6.4784,  2.7144,
         2.1365,  1.7746,  0.8174, -0.1890])
tensor([0.1233, 0.2329, 0.5821, 4.8679, 5.0413, 6.6911, 1.1023, 0.1491, 0.4810,
        0.4149, 0.0292, 0.2739, 0.2187, 0.2812, 7.1856, 0.4726, 5.9926, 1.4980,
        2.1760, 0.6822], grad_fn=<SliceBackward0>)
tensor([-0.2025,  0.9037,  0.3512,  4.0077,  7.0383, 10.1098,  3.9418,  1.3813,
         1.4037, -0.1789,  0.0283, -0.1101,  0.0604, -0.3565, 15.9957, -0.0403,
         7.5601,  2.0390,  2.5036, -0.1281])
tensor([ 0.9096,  0.3858,  0.7258,  6.7796,  6.7780, 10.4541, 12.5208,  0.2022,
         0.5438,  0.8404,  0.1514,  0.2534,  0.6601,  0.3826, 11.3274,  0.7128,
        

tensor([ 0.3519,  0.4267,  0.9021,  5.9830,  6.1026, 11.9684,  4.8246,  0.3449,
         0.5962,  1.8876,  0.1849,  0.2955,  1.0514,  0.5251,  6.1012,  0.7014,
         9.4090,  4.1134,  5.9424,  0.4215], grad_fn=<SliceBackward0>)
tensor([ 1.6144, -1.0589,  1.2447,  6.8182,  7.3015, 17.1236,  7.9310, -0.9190,
         0.9149,  0.6967, -1.2728, -0.7319, -0.3818, -1.1413,  9.0919, -0.5426,
         8.9026,  3.3801,  8.1243, -0.5297])
tensor([ 0.6119,  0.4275,  0.9225,  6.6229,  6.4710, 10.2322,  8.8543,  0.3056,
         0.6999,  1.3498,  0.1517,  0.3358,  0.7807,  0.5320,  8.6148,  0.7065,
         8.6293,  5.5648,  4.7461,  0.4562], grad_fn=<SliceBackward0>)
tensor([ 0.1593,  1.7591,  0.9939,  6.0072,  4.2517,  5.9201,  8.0657,  0.4221,
         0.8790,  0.9259, -0.2128,  2.5523,  0.3991,  0.1982, 12.4918,  7.0738,
         8.4164,  5.3948,  3.0479,  0.1655])
tensor([1.2564, 0.2944, 0.5327, 4.7805, 4.0248, 5.4705, 8.5385, 0.2017, 0.3327,
        0.3916, 0.0980, 0.2929, 0.2619, 0.3350, 

tensor([ 0.4266,  0.5012,  1.0664,  7.4885,  5.8546,  9.0436,  3.3524,  0.3373,
         1.0464,  0.4224,  0.0683,  0.5379,  0.5040,  0.6430, 14.1043,  1.3283,
         6.8389,  1.9579,  1.6286,  0.7855], grad_fn=<SliceBackward0>)
tensor([-0.7111, -0.0265, -0.0426, 10.3651,  4.6951, 11.2124,  4.6209, -0.6015,
         0.6290, -0.5949, -1.0650, -0.7098,  1.4385, -1.0985, 18.7231,  6.2651,
         7.2349,  1.7539,  4.2174, -0.4725])
tensor([ 1.4536,  0.6388,  1.3576,  8.7603,  5.9071, 10.1632,  7.1479,  0.4177,
         1.3291,  0.9300,  0.1016,  0.7154,  0.6327,  0.8218, 15.7781,  3.3869,
         6.2640,  0.3677,  2.3154,  0.5992], grad_fn=<SliceBackward0>)
tensor([ 1.2114,  0.8756,  1.1085,  9.5224,  5.6098,  7.2096,  5.2286,  1.2335,
         0.5552,  1.9042,  0.0374, -0.0995, -0.5269,  0.5683, 19.0809, -0.0781,
         3.7501,  0.1272,  0.0329, -0.1253])
tensor([0.2670, 0.3234, 0.6365, 5.0637, 5.3446, 7.4617, 1.7616, 0.2107, 0.5170,
        0.5864, 0.1115, 0.3167, 0.3309, 0.3502, 

tensor([ 0.7415,  0.2076,  0.3705,  5.4372,  5.1406,  5.1720, 12.2268,  0.1036,
         0.2560, -0.0439,  0.0283,  0.2004,  0.1412,  0.2089,  9.7307,  0.5063,
         4.8131,  4.4235,  0.5867,  0.1536], grad_fn=<SliceBackward0>)
tensor([ 1.8115,  0.8812,  0.6530,  6.6095,  6.9856,  8.3775, 14.7029, -1.2864,
         1.0465, -0.1000, -0.4560,  2.4768, -0.1104, -0.0639, 10.2806, -0.3984,
         6.6704,  5.9251,  2.0225, -0.4172])
tensor([ 0.1448,  0.6194,  1.0182,  3.5030,  3.3404,  4.1329,  0.2244,  0.8142,
         1.0145,  0.2159, -0.0642,  0.5862,  0.5013,  0.6497,  4.2372,  0.1878,
         3.5912,  0.3480,  1.1230,  0.5779], grad_fn=<SliceBackward0>)
tensor([-0.1088,  0.0370,  0.9140,  0.1444,  3.1278,  4.2260, -0.6716,  0.3819,
         2.4136,  0.4617, -0.5406,  1.6040, -0.3232,  1.4032,  9.2578,  0.0258,
         0.8752, -0.6981,  1.0300, -0.0876])
tensor([0.2594, 0.2513, 0.5580, 4.1836, 4.8294, 8.7798, 4.2795, 0.1987, 0.3730,
        1.0640, 0.1257, 0.2197, 0.6321, 0.3435, 

tensor([0.3187, 0.3059, 0.5585, 4.3121, 4.7499, 6.4008, 1.9910, 0.2113, 0.4266,
        0.5784, 0.1072, 0.2821, 0.2999, 0.3110, 5.7205, 0.7467, 5.8924, 1.9988,
        2.3803, 0.5157], grad_fn=<SliceBackward0>)
tensor([-0.4116, -0.8775,  1.2095,  5.3698,  5.3086,  5.5950,  1.0756, -0.4542,
         0.0108, -0.4291,  0.4110, -0.3323,  0.9379,  1.6297,  7.4033, -0.1977,
         6.2155,  1.3587,  0.9391, -0.2695])
tensor([0.0424, 0.3096, 0.7072, 3.3081, 4.2134, 2.5507, 0.0820, 0.7823, 0.4587,
        0.1653, 0.0477, 0.3077, 0.2374, 0.3196, 2.6326, 0.2479, 3.8222, 0.2666,
        1.1386, 0.5296], grad_fn=<SliceBackward0>)
tensor([ 2.8827,  0.5201,  1.9038,  4.4084,  5.3445,  1.8607,  0.8845,  0.3811,
         0.9547, -0.7404, -1.1353, -0.6086,  0.2248,  1.2889,  0.9363, -0.3936,
         3.0553, -0.0204,  0.6833, -0.4455])
tensor([0.3000, 0.7699, 1.5186, 8.8080, 7.6475, 7.6589, 0.1669, 0.7007, 1.2339,
        1.6073, 0.1775, 0.6999, 0.8476, 0.8001, 5.8008, 1.2109, 8.1755, 0.9007,
        

tensor([0.3339, 0.6494, 1.0551, 6.4920, 6.0219, 7.5353, 0.6616, 0.5919, 0.8223,
        1.5672, 0.2378, 0.5495, 0.7856, 0.6289, 2.6025, 0.9211, 6.6383, 0.2424,
        4.7676, 0.2454], grad_fn=<SliceBackward0>)
tensor([0.2285, 2.2041, 1.9204, 6.1587, 6.9200, 7.8527, 1.5115, 0.8322, 1.8127,
        4.4890, 0.6074, 2.6216, 1.3763, 2.5589, 2.6739, 3.5693, 6.9502, 1.3670,
        5.3609, 0.2196])
tensor([0.3053, 0.2382, 0.6511, 5.5218, 5.8210, 9.5036, 6.0212, 0.1842, 0.4480,
        1.1211, 0.0938, 0.2095, 0.5596, 0.3318, 6.5624, 0.4980, 7.6750, 4.0896,
        4.3944, 0.3969], grad_fn=<SliceBackward0>)
tensor([ 1.1231,  0.2742,  0.1249,  3.6735,  7.0212,  7.9975, -0.2933,  0.3890,
        -0.4138, -0.1378,  0.0648, -0.0737, -0.3461, -0.3115,  2.0153, -0.0144,
         7.6006,  0.1418,  3.7144, -0.1049])
tensor([ 3.7591e-01,  7.6456e-01,  1.2751e+00,  4.9107e+00,  3.9808e+00,
         4.3979e+00,  3.6628e-01,  6.3901e-01,  1.3804e+00,  4.5689e-01,
        -3.1307e-04,  8.7392e-01,  6.4788e

tensor([ 0.5197,  1.0851,  1.7733,  8.3699,  5.2372,  8.5075,  1.3632,  0.7879,
         1.9873,  0.7358, -0.1876,  1.1056,  0.7415,  1.1740, 13.4957,  1.7984,
         5.0327,  0.5233,  1.9844,  0.5832], grad_fn=<SliceBackward0>)
tensor([-0.8079,  1.5352,  1.3585,  6.1129,  6.0824,  6.4238, -0.7407,  0.7079,
         1.9979,  1.2378,  0.6554, -0.8245, -0.9445, -0.0865, 16.2545, -0.5698,
         3.4898, -0.2462, -0.9207,  3.1679])
tensor([0.3640, 0.3122, 0.4723, 4.2702, 4.2861, 6.8313, 3.3955, 0.1793, 0.3332,
        0.3348, 0.1334, 0.2706, 0.4141, 0.2929, 7.6470, 0.9200, 6.0611, 1.7929,
        1.3294, 0.2612], grad_fn=<SliceBackward0>)
tensor([-0.5478,  1.3016,  0.8718,  4.6593,  4.9753,  3.9139,  2.2260,  0.8988,
         0.4423, -1.1783,  1.0239, -0.4857,  0.1303,  1.6967,  8.0597, -0.3116,
         0.7907,  2.2795, -0.0354, -0.3644])
tensor([ 0.2841,  0.6515,  1.3123,  6.5258,  4.3578,  6.7557,  0.7211,  0.4372,
         1.4315,  0.3446, -0.1215,  0.8384,  0.5283,  0.9178, 11.814

tensor([ 1.2565,  0.4241,  0.9255,  6.3274,  4.5244,  7.1555,  6.3072,  0.2880,
         0.8565,  0.6284,  0.0466,  0.5012,  0.4035,  0.5489, 11.2143,  2.3110,
         4.2616,  0.0235,  1.5060,  0.4613], grad_fn=<SliceBackward0>)
tensor([ 0.8553,  0.3236, -0.1857,  5.8906,  4.3827,  7.7026,  4.1765, -1.2435,
         0.6392,  0.5796, -0.8034, -0.1349, -0.0212, -0.5040, 11.5988, -0.0433,
         5.7971,  0.2036,  1.6826, -0.1998])
tensor([ 0.2248,  0.6537,  1.1480,  4.2686,  3.1385,  4.5871,  0.2779,  0.5377,
         1.2822,  0.2239, -0.1073,  0.7542,  0.5316,  0.8246,  6.7085,  0.3236,
         3.1346,  0.5311,  0.9453,  0.6267], grad_fn=<SliceBackward0>)
tensor([ 0.7894,  1.3607,  2.2107,  2.8319,  1.9667,  0.1333, -0.8238,  0.2895,
         0.6724,  0.5023,  0.8028,  1.1567,  0.5937,  1.4739,  3.2766,  2.3391,
         0.5538,  1.9483, -0.2280,  1.8852])
tensor([ 1.2312,  0.3828,  0.7923,  6.0490,  4.6735,  7.5568,  7.0443,  0.2703,
         0.6601,  0.5878,  0.1108,  0.3758,  0.4

tensor([0.2183, 0.5334, 0.8443, 4.9537, 5.6478, 7.0136, 0.2107, 0.3932, 0.6777,
        1.2419, 0.2211, 0.4476, 0.6151, 0.4966, 3.1678, 0.5864, 6.2138, 0.8678,
        4.1494, 0.3931], grad_fn=<SliceBackward0>)
tensor([ 1.3907e+00,  1.0925e+00,  1.4292e+00,  3.0656e+00,  4.7722e+00,
         5.5075e+00, -7.2897e-01,  5.6026e-01,  2.1794e+00,  6.5274e-01,
         3.4600e-01,  1.8087e+00,  8.5044e-01, -2.8537e-03,  1.6588e+00,
         5.5643e+00,  4.1391e+00,  1.4659e+00,  3.1654e+00,  2.4759e-02])
tensor([ 0.1399,  0.3560,  0.7147,  3.2800,  3.4863,  2.6966,  0.3279,  0.6214,
         0.6234,  0.1722, -0.0512,  0.3697,  0.2832,  0.4106,  4.1322,  0.3027,
         2.9012,  0.0683,  0.9056,  0.5654], grad_fn=<SliceBackward0>)
tensor([-0.4823,  0.3950, -0.6398,  3.1269,  4.8717,  6.7304, -0.5862, -0.0903,
         0.8342,  1.3020,  0.4706,  1.2890, -0.2489, -0.7524,  8.1343, -0.2555,
         2.8195,  0.6869,  0.0152, -0.3211])
tensor([ 0.2204,  0.6507,  1.2258,  5.4862,  5.0017,  4.2282

tensor([ 0.0224,  0.3059,  0.7807,  4.6952,  5.0352,  3.7342, -0.3788,  0.5693,
         0.4991,  0.4739,  0.0708,  0.3286,  0.2804,  0.3257,  2.9415,  0.3725,
         4.7571,  0.1536,  2.0639,  0.4395], grad_fn=<SliceBackward0>)
tensor([-1.0291e-02,  5.0645e-01,  1.1404e+00,  6.7373e+00,  4.5073e+00,
         1.8132e+00, -1.7730e-01, -2.2020e-02, -4.0290e-01,  5.1069e-02,
         2.3309e-01,  9.4027e-02, -1.3134e-01, -1.0466e-01,  5.3751e-01,
         1.0442e-01,  2.3986e+00,  2.9561e-01,  1.3337e+00,  1.9222e-03])
tensor([0.1242, 0.1742, 0.4615, 4.2580, 4.4474, 7.2908, 2.7043, 0.2313, 0.3249,
        0.9556, 0.0760, 0.2083, 0.4777, 0.3287, 3.0924, 0.6098, 5.6240, 1.5957,
        3.5084, 0.1798], grad_fn=<SliceBackward0>)
tensor([ 0.0594,  0.2286,  0.1648,  3.9792,  2.2954,  7.7815,  1.4215,  0.6340,
        -0.2979,  0.6782,  1.4701,  0.1680,  0.4165,  0.8077,  7.0978,  0.1569,
         2.9911,  0.6920,  1.4022,  0.0490])
tensor([ 0.4034,  0.1592,  0.6488,  6.3458,  6.3989, 10.7108

tensor([ 0.1391,  0.5304,  1.0949,  5.2048,  4.9308,  3.9320,  0.3237,  0.6396,
         1.0538,  0.3221, -0.0415,  0.5997,  0.4347,  0.6252,  7.4260,  0.3314,
         4.0391,  0.5790,  1.5003,  0.7320], grad_fn=<SliceBackward0>)
tensor([ 1.1151,  0.3713,  3.2579,  5.7356,  5.9890,  8.4209,  0.7868,  0.0822,
         1.1185,  0.6917,  0.7022,  5.3703,  1.8384,  2.0111, 12.6809, -0.5255,
         7.1970, -1.5193, 10.0587, -0.5085])
tensor([ 1.5406,  0.5805,  1.1304,  7.3928,  5.2977,  9.1144,  7.2674,  0.3981,
         1.0604,  0.9456,  0.1799,  0.5915,  0.6162,  0.6867, 12.9394,  3.2598,
         5.9814,  0.3374,  2.0981,  0.4704], grad_fn=<SliceBackward0>)
tensor([ 4.7831,  0.8439,  1.3834,  8.5672,  5.4709, 11.3913, 15.8650,  0.9576,
         1.6630,  1.1557, -0.2130, -0.4390, -0.3563,  0.1559, 21.0069, -0.2495,
         8.0627,  1.5588,  1.5804,  2.3521])
tensor([ 0.1039,  0.5199,  1.0013,  4.9183,  3.3718,  5.2901,  0.2933,  0.4759,
         1.1290,  0.0900, -0.2764,  0.5511,  0.3

tensor([0.1437, 0.3042, 0.5543, 3.2701, 3.9346, 4.0104, 0.0502, 0.2953, 0.4223,
        0.6144, 0.1261, 0.3196, 0.3161, 0.3473, 1.8864, 0.4178, 3.8806, 0.3737,
        2.1367, 0.3733], grad_fn=<SliceBackward0>)
tensor([-0.2495, -0.2257, -1.3262,  4.6484,  4.8755,  2.3676, -0.3530, -0.2797,
         0.2551,  0.8088, -0.6853, -0.1601,  1.4944, -0.4181,  0.0249, -0.0757,
         2.1165, -1.0858,  1.0985, -0.1599])
tensor([ 0.3578,  0.7470,  1.3477,  6.9841,  5.9747,  6.9256,  0.5826,  0.4984,
         1.3554,  0.7151,  0.0936,  0.8052,  0.6365,  0.8835, 10.6773,  1.0544,
         5.7815,  1.7136,  2.3141,  0.9084], grad_fn=<SliceBackward0>)
tensor([ 0.8958, -0.3004,  1.3171,  9.8562,  6.3833,  8.0732,  0.7426,  3.0945,
         1.9012,  1.0923,  0.5204,  2.9832, -0.1283,  3.2572, 17.6574, -0.4092,
         8.6499,  5.4355,  6.9902, -0.4594])
tensor([ 0.0200,  0.2164,  0.6656,  5.1670,  4.8260,  4.9251,  0.2373,  0.3149,
         0.4788,  0.6176,  0.0283,  0.3169,  0.2532,  0.3151,  2.480

tensor([0.2621, 0.2427, 0.4937, 4.4550, 5.0031, 6.7140, 3.2384, 0.1703, 0.3637,
        0.6237, 0.0880, 0.2378, 0.2784, 0.2585, 5.3652, 0.6446, 5.9957, 2.3901,
        2.8368, 0.3992], grad_fn=<SliceBackward0>)
tensor([ 1.0873e+00, -2.0540e-01,  2.7472e-03,  4.3923e+00,  5.1320e+00,
         7.4742e+00,  1.2561e+01, -1.7154e-01, -7.9564e-01,  3.9539e-01,
        -6.5555e-01, -9.1905e-02,  4.3898e-01,  1.2235e+00,  1.0113e+01,
         6.3775e-02,  4.5998e+00,  4.1649e+00,  4.3199e-01,  9.0695e+00])
tensor([ 0.1492,  0.6214,  1.2024,  5.1090,  3.5486,  5.4748,  0.3668,  0.4340,
         1.3599,  0.1831, -0.1677,  0.7842,  0.4908,  0.8455,  8.7125,  0.3075,
         3.3974,  0.4738,  0.9842,  0.7112], grad_fn=<SliceBackward0>)
tensor([ 0.0483,  0.9461,  1.7921,  5.2805,  1.1222, -1.4809,  0.8858,  1.4044,
         0.5495, -0.7225, -1.7557, -1.2937, -0.4851,  1.4072,  9.3193, -0.9944,
        -1.4089,  0.7565,  0.1745,  4.3269])
tensor([ 0.1945,  0.8098,  1.3167,  4.4299,  2.7525,  5.6785

tensor([0.0774, 0.1888, 0.4469, 4.1661, 4.7171, 6.3098, 1.5936, 0.2021, 0.3199,
        0.7906, 0.0764, 0.2175, 0.2869, 0.2462, 2.9827, 0.5635, 5.2117, 0.9455,
        3.2905, 0.2083], grad_fn=<SliceBackward0>)
tensor([ 0.3677,  0.4379, -0.2080,  6.7054,  5.5469, 10.6968,  0.6995,  1.0655,
         1.6528,  0.4655, -1.4036,  0.6743, -1.3734,  0.2694,  2.0547,  2.0321,
         7.8870,  0.3303,  3.5060, -0.6158])
tensor([0.3769, 0.5463, 1.0059, 6.6373, 6.6590, 9.1810, 3.7826, 0.3849, 0.7927,
        1.5524, 0.1851, 0.4593, 0.7082, 0.5520, 6.3649, 0.9839, 7.9435, 2.8632,
        5.1394, 0.3749], grad_fn=<SliceBackward0>)
tensor([-0.0656,  0.9478,  0.6295,  6.1947,  5.8424,  9.3150,  1.0861, -0.6543,
         0.7724,  0.7123, -0.4330,  0.0557,  0.0867, -0.1369,  4.9186,  0.1198,
         6.6431,  5.6830,  6.9564,  3.7120])
tensor([ 0.5375,  1.1339,  1.8134,  8.1408,  7.4763,  6.8126,  0.4691,  1.5947,
         1.7282,  0.6098, -0.0401,  0.9636,  0.7616,  1.0187,  9.8499,  0.5875,
        

tensor([0.2735, 0.3045, 0.6433, 4.7386, 4.4546, 6.6801, 1.3786, 0.2165, 0.5529,
        0.3377, 0.0645, 0.3198, 0.3038, 0.3769, 8.3732, 0.7368, 5.6132, 1.3769,
        1.4181, 0.7013], grad_fn=<SliceBackward0>)
tensor([-0.1677,  0.4835, -0.5003,  6.1624,  4.9882,  4.2267,  3.4596,  0.2354,
        -0.0459,  2.1318, -0.6316, -0.1007, -0.3418, -0.3560,  7.3047,  0.0139,
         3.0486,  0.5508,  1.0833,  2.6156])
tensor([ 4.8927e-02,  5.4093e-01,  9.7201e-01,  3.8642e+00,  2.2262e+00,
         4.8758e+00,  2.4855e-01,  3.8963e-01,  1.1567e+00, -4.3041e-03,
        -2.8223e-01,  6.2498e-01,  3.7981e-01,  6.6014e-01,  5.9134e+00,
        -2.4041e-02,  2.5865e+00,  2.4977e-01,  5.2739e-01,  4.7063e-01],
       grad_fn=<SliceBackward0>)
tensor([ 0.5858,  0.1639,  1.8540,  2.5497,  1.1604,  0.9785,  0.8597, -0.7707,
         1.4813, -0.7807, -0.5079,  0.9059, -0.2069,  0.5551,  0.8640, -0.4190,
         0.4385, -0.0532, -0.1168, -0.4683])
tensor([ 0.4034,  0.3698,  0.9681,  7.5951,  7.4372, 

tensor([0.3959, 0.2736, 0.4641, 4.6816, 4.4867, 6.7108, 4.8261, 0.1482, 0.3395,
        0.2308, 0.0934, 0.2434, 0.3501, 0.2594, 8.6077, 0.8018, 5.7841, 2.0450,
        1.1184, 0.2809], grad_fn=<SliceBackward0>)
tensor([-0.0548,  0.2386,  0.6071,  4.5195,  3.3443, -0.4190,  4.6023,  1.8820,
        -0.3048,  2.2521,  0.2093,  0.0136,  0.7769,  0.7058,  8.6215,  0.1105,
         6.1181,  1.8330, -0.5590, -0.0381])
tensor([ 0.8766,  0.9094,  1.5880,  9.7430,  8.3363, 11.9598,  8.1853,  0.6381,
         1.4302,  1.7280,  0.3079,  0.7782,  1.0757,  1.0371, 13.6800,  2.0718,
        10.8599,  5.8533,  5.3633,  0.5768], grad_fn=<SliceBackward0>)
tensor([ 1.5007,  0.0619,  1.4301,  5.1569,  3.8262, 11.3457,  7.1002, -0.1096,
        -0.1539,  3.9446,  1.0765,  0.3516,  0.4978,  0.1429,  4.3571,  0.1496,
         5.4117,  7.8985,  2.4357,  0.1352])
tensor([0.3585, 0.5735, 0.9815, 5.6575, 5.6633, 6.7221, 0.9375, 0.3928, 0.9104,
        0.8201, 0.1681, 0.5553, 0.5243, 0.6105, 6.9348, 0.8620, 6.08

tensor([ 0.1396,  0.2722,  0.7785,  5.6932,  4.7592,  6.8795,  1.0344,  0.1949,
         0.7171,  0.2488, -0.0552,  0.3526,  0.2146,  0.3997, 10.5247,  0.6870,
         5.2906,  1.0117,  1.2155,  0.9094], grad_fn=<SliceBackward0>)
tensor([-0.3182,  1.8997,  0.7426,  6.5464,  5.5499,  6.2061,  0.7382,  0.1577,
         1.3349,  0.7762,  0.5545,  2.6858,  0.6502,  0.2929, 14.3168, -0.0902,
         4.1802,  3.5461, -0.7755, -0.2194])
tensor([ 0.3765,  0.6830,  1.3754,  8.8040,  7.9435, 10.6224,  2.5785,  0.5674,
         1.0555,  2.1911,  0.2145,  0.5408,  0.9355,  0.7396,  6.2712,  1.3005,
         9.6559,  1.8553,  6.7769,  0.3086], grad_fn=<SliceBackward0>)
tensor([-0.4259,  1.2065,  1.3986,  7.5904,  8.7227,  8.5583, -0.7005, -0.6218,
         0.2654,  1.3997,  0.7818, -0.3203,  0.8106,  0.3623,  4.2097, -0.1599,
         7.9775, -0.9052,  0.7713, -0.2590])
tensor([1.1712, 0.3402, 0.6625, 5.2969, 3.9794, 6.9356, 6.5953, 0.2174, 0.5057,
        0.5597, 0.1085, 0.3309, 0.3902, 0.3527, 

tensor([-0.0070,  0.5841,  0.9738,  3.7912,  1.9403,  5.2106,  0.0676,  0.3921,
         1.1813, -0.0062, -0.2927,  0.6362,  0.4194,  0.6770,  5.6755, -0.0632,
         2.5924,  0.2309,  0.4452,  0.3993], grad_fn=<SliceBackward0>)
tensor([-2.2535,  0.0321,  0.7866,  1.1117,  1.9841,  5.9770, -2.7720,  0.1311,
         0.9381,  0.2954, -1.0059, -0.6378, -1.0912,  1.2211,  4.7096, -2.1199,
         1.2571, -0.6918, -2.0324,  3.3352])
tensor([0.4036, 0.2654, 0.6102, 6.1226, 6.3217, 8.1982, 6.8271, 0.1502, 0.4762,
        0.5914, 0.0658, 0.2448, 0.2987, 0.2659, 8.8205, 0.6634, 7.5317, 3.8509,
        3.0688, 0.4594], grad_fn=<SliceBackward0>)
tensor([-0.3788,  0.7369, -0.3273,  8.6412,  7.0354,  9.5051,  6.7215,  0.6522,
         0.8098,  1.1702, -0.8100, -0.2832,  0.6480,  1.0397,  7.9656, -0.1756,
         7.3847,  5.6659,  0.8782, -0.2616])
tensor([ 0.5569,  0.3479,  0.6695,  6.3330,  6.0036,  7.9812,  7.6719,  0.2048,
         0.5858,  0.3181,  0.1051,  0.3149,  0.3779,  0.3645, 11.123

tensor([ 0.1497,  0.5070,  0.8082,  2.9552,  1.7082,  3.8564,  0.1764,  0.3561,
         0.9182,  0.0774, -0.1873,  0.5797,  0.3882,  0.6106,  3.8738,  0.1599,
         2.1700,  0.3260,  0.4822,  0.3960], grad_fn=<SliceBackward0>)
tensor([-1.0879,  0.4911,  0.2782,  4.6696,  3.4345,  2.6632, -0.5848, -0.1684,
         2.1412,  1.1505,  0.5083,  0.6755,  0.9806, -0.5957,  0.5457, -0.7741,
         0.3973, -0.0191,  1.1323, -0.7220])
tensor([0.4234, 0.7196, 1.1512, 6.2887, 6.1764, 7.7518, 0.8376, 0.4855, 1.0978,
        0.9334, 0.2421, 0.6849, 0.6846, 0.7691, 8.1291, 1.1059, 7.1064, 2.3936,
        3.2417, 0.7312], grad_fn=<SliceBackward0>)
tensor([-0.5093,  0.5868,  2.9021,  5.1426,  5.2270, 10.0682, -0.6617, -0.0793,
         2.6554, -0.5535,  0.7022,  3.2735, -0.9350,  1.1621, 12.4177, -0.2357,
        10.8265,  7.2420,  4.1155, -0.3200])
tensor([ 0.7199,  0.3006,  0.5155,  5.6597,  5.7187,  6.5031, 10.9805,  0.1699,
         0.3784,  0.3300,  0.0799,  0.2347,  0.2980,  0.2494,  9.111

tensor([ 0.4071,  0.3937,  1.0116,  8.4374,  7.7205, 10.7879,  6.6795,  0.2609,
         0.8433,  1.0622,  0.0770,  0.3701,  0.4943,  0.4822, 12.0249,  1.0209,
         9.4851,  4.1834,  4.4977,  0.6463], grad_fn=<SliceBackward0>)
tensor([-0.2217,  0.2626,  0.9813,  6.9308,  5.1619,  7.9168,  6.6698, -0.9781,
         0.7175,  2.6071,  0.0593, -0.0988,  0.8657,  1.2512,  6.9433, -0.0584,
         8.9837,  1.0562,  1.6973, -0.1604])
tensor([0.3582, 0.6919, 1.1187, 6.7040, 6.9430, 9.8588, 2.1273, 0.4862, 0.9004,
        1.7603, 0.2782, 0.5503, 0.8751, 0.6515, 5.8097, 1.0322, 8.4047, 2.4228,
        5.6982, 0.4149], grad_fn=<SliceBackward0>)
tensor([-0.1029,  2.3234,  1.5319,  4.2571,  4.1737,  7.3168, -0.8508,  1.5664,
         0.9318,  1.1907, -0.5835,  0.1717,  0.8392,  1.9314,  4.8932,  0.1340,
         7.2585,  2.9607,  7.9341, -0.0228])
tensor([ 0.2670,  0.7435,  1.2926,  5.7435,  4.2168,  5.7402,  0.3856,  0.7043,
         1.4518,  0.2898, -0.1838,  0.7604,  0.5474,  0.8494,  8.889

tensor([ 2.7449,  0.4056,  0.6834,  4.4157,  4.3882, 10.2648, 16.9246,  0.2864,
         0.4103,  0.8970,  0.2556,  0.1356,  0.6611,  0.9152,  9.6485, -0.6014,
         9.0758,  8.9076,  2.3641,  0.3759], grad_fn=<SliceBackward0>)
tensor([ 3.8494e+00, -1.8410e-01,  8.6563e-01,  3.9655e+00,  4.2386e+00,
         1.3158e+01,  1.3520e+01, -7.6289e-03,  5.5308e-01,  7.2813e-01,
        -6.6204e-01,  3.0238e-03,  1.4552e+00,  4.0011e-01,  1.3962e+01,
         2.4933e+00,  1.0408e+01,  9.7834e+00,  2.7973e+00, -1.2002e-01])
tensor([ 0.3283,  0.9425,  1.8082,  8.4937,  7.3498,  6.2070,  0.5462,  1.0411,
         1.7712,  0.5532, -0.0549,  1.0478,  0.7204,  1.0576, 12.1656,  0.7659,
         6.2134,  1.2562,  2.7468,  0.8337], grad_fn=<SliceBackward0>)
tensor([-1.7035,  0.5367,  1.1620,  5.4820,  5.0787,  6.4613, -0.1058,  1.0293,
         0.8381,  0.9958, -1.2357,  3.0878,  1.7583, -2.0566, 12.9385,  1.8112,
         7.3650,  0.2069,  1.2474, -1.1936])
tensor([0.2907, 0.6690, 1.2559, 7.6923, 

tensor([0.2113, 0.4717, 0.9044, 6.5345, 6.6256, 8.9366, 1.9615, 0.3757, 0.6809,
        1.5596, 0.1660, 0.3866, 0.6260, 0.4595, 4.7463, 0.8764, 7.5671, 1.2973,
        5.2695, 0.3168], grad_fn=<SliceBackward0>)
tensor([-0.3588,  0.4198, -0.9402,  8.0177,  6.1844, 10.5975,  0.8920,  0.6726,
        -0.0263,  2.4569,  1.1713, -0.2598,  0.2622,  0.2834,  5.6080, -0.1607,
         5.1394,  0.6884,  2.9266, -0.2487])
tensor([0.2634, 0.2211, 0.5309, 4.9551, 5.3246, 6.8266, 3.8236, 0.1660, 0.4041,
        0.6415, 0.0677, 0.2304, 0.2373, 0.2568, 5.7618, 0.6635, 5.9974, 2.4303,
        2.9908, 0.3873], grad_fn=<SliceBackward0>)
tensor([-0.4807,  0.1469, -0.6715,  3.6163,  3.3982,  3.0897,  1.0059, -0.4896,
        -0.3675,  0.5761,  0.2909, -0.3952,  0.4487,  2.2070, -0.4391, -0.2480,
         2.7020,  2.1801,  0.0801,  2.2837])
tensor([ 0.1534,  0.4925,  0.9926,  4.2169,  3.1035,  4.4099,  0.4457,  0.4588,
         1.1007,  0.0684, -0.2174,  0.5861,  0.3429,  0.6322,  6.8346,  0.1147,
        

tensor([ 0.2097,  0.2053,  2.7653,  3.5306,  5.4110,  9.4367,  0.5834, -0.0603,
         2.0975,  1.1108,  0.7698,  0.5064, -1.5884, -0.6873,  3.2411,  1.9131,
         5.9950,  1.8182,  3.3506, -0.7228])
tensor([0.4020, 0.3592, 0.4670, 2.9369, 3.4341, 4.4719, 0.9321, 0.2459, 0.3165,
        0.4997, 0.1544, 0.3043, 0.3153, 0.3366, 3.5038, 0.7432, 4.2564, 1.2996,
        1.5304, 0.4325], grad_fn=<SliceBackward0>)
tensor([ 0.9623,  1.0864, -0.2878,  3.3188,  1.5543,  4.9545,  0.3068,  1.3322,
         0.5268, -0.3123,  0.9959, -0.0183,  0.1173,  1.0589,  6.3386,  0.0425,
         7.2622,  2.4956, -0.8574, -0.1324])
tensor([ 0.5996,  0.3101,  0.6653,  6.9845,  6.8759,  9.1436,  9.9867,  0.1733,
         0.5244,  0.5827,  0.0949,  0.2559,  0.3778,  0.3036, 11.1101,  0.8895,
         8.4172,  4.9975,  2.9863,  0.4035], grad_fn=<SliceBackward0>)
tensor([-0.3106, -0.4215,  0.6440,  5.1754,  6.8857, 10.1680, 11.4618,  0.3224,
         0.4694, -1.0566,  0.3275, -0.1704,  1.2491, -0.5443, 14.966

tensor([0.1681, 0.3067, 0.3916, 1.6212, 1.6798, 1.6486, 0.0601, 0.3200, 0.2431,
        0.1172, 0.0226, 0.3845, 0.2685, 0.3967, 1.0122, 0.3811, 1.9127, 0.4635,
        0.4138, 0.3620], grad_fn=<SliceBackward0>)
tensor([ 6.4726e-03, -6.1310e-01, -9.9216e-01,  1.6959e+00,  1.9382e+00,
         5.1242e+00, -5.8732e-01, -8.3433e-01, -4.4627e-01,  7.1886e-01,
         2.6781e-01,  7.5714e-02, -1.1336e-01,  7.8300e-01,  3.8226e-02,
         1.6300e-01,  1.9049e+00, -7.5204e-02, -5.1170e-01,  2.4836e-03])
tensor([0.2281, 0.4629, 0.7954, 5.4815, 6.2193, 9.3825, 2.2739, 0.3187, 0.5670,
        1.4085, 0.1981, 0.3530, 0.6556, 0.3922, 4.9841, 0.6104, 7.7706, 2.2786,
        5.1111, 0.4098], grad_fn=<SliceBackward0>)
tensor([ 1.2654, -0.3249, -0.1402,  0.1891,  3.2606,  6.5424, -0.6877, -0.8124,
        -0.4407, -0.0513, -0.4915,  0.0915,  0.6769, -0.1715,  7.0721,  0.0625,
         0.8993, -0.6785,  4.2376, -0.0559])
tensor([ 0.8275,  0.3563,  0.5161,  5.6560,  5.8161,  6.8443, 11.6215,  0.2025,


tensor([0.4162, 0.3461, 0.7560, 6.4599, 6.5513, 8.8443, 6.0070, 0.2190, 0.5859,
        0.9280, 0.0992, 0.2999, 0.3993, 0.3435, 8.4134, 0.8021, 7.7554, 3.7590,
        3.9004, 0.4947], grad_fn=<SliceBackward0>)
tensor([ 3.0809e-02, -2.7522e-01,  2.2585e+00,  7.3547e+00,  7.2860e+00,
         8.8306e+00,  3.1166e+00, -6.0985e-02,  1.6785e+00,  1.6616e+00,
        -3.8558e-01,  1.3909e-01,  2.1484e+00,  2.8130e+00,  1.5271e+00,
         2.3170e-01,  7.4022e+00,  7.7615e-01,  3.9692e+00,  1.3542e-03])
tensor([ 0.2213,  0.4602,  0.5921,  3.0009,  2.6777,  3.7393,  0.0050,  0.6673,
         0.4784,  0.1520, -0.1039,  0.3571,  0.3162,  0.4344,  2.9294,  0.0686,
         3.3538,  0.5361,  0.6296,  0.4977], grad_fn=<SliceBackward0>)
tensor([-0.4483,  0.0696,  0.2503,  2.3836,  1.1898,  6.3549,  0.3858, -0.3014,
         0.4103, -0.1077,  0.1738, -0.3205, -0.2416,  0.7169,  4.3323, -0.1797,
         3.1366, -0.6048, -0.2939, -0.3072])
tensor([ 0.5569,  0.5934,  1.0286,  6.7201,  5.8588,  8.1536

tensor([ 0.4365,  0.9291,  1.6499,  8.5990,  7.1371,  8.2110,  0.7325,  0.6197,
         1.6413,  1.0229,  0.1426,  0.9733,  0.8208,  1.0629, 12.0295,  1.4555,
         7.1190,  2.1938,  3.2490,  0.8910], grad_fn=<SliceBackward0>)
tensor([ 0.9902,  1.9676,  4.3734,  8.9070,  7.6336, 10.7329,  0.6987,  0.3956,
         0.4624,  1.1982, -0.1882,  3.1269,  0.9803,  0.9799, 16.6077, 10.7394,
         9.0742,  5.1565,  2.8844,  9.5250])
tensor([0.3853, 0.7624, 1.2278, 7.1142, 6.8073, 8.5838, 0.9088, 0.5915, 1.0004,
        1.9027, 0.2780, 0.6136, 0.8969, 0.7323, 4.0133, 1.1479, 7.4888, 0.9061,
        5.5881, 0.2814], grad_fn=<SliceBackward0>)
tensor([-0.3234,  0.9943,  1.8464, 11.1060,  8.6927,  5.7542,  0.5673, -0.4952,
         1.2193,  0.9433,  0.0810,  1.7810, -1.2702,  2.3950, -0.1602, -0.0666,
         8.8304, -0.8621,  8.2617, -0.1840])
tensor([ 1.5625,  0.4453,  0.8965,  4.7816,  4.8347, 13.4853, 11.3466,  0.3158,
         0.5949,  1.7467,  0.2399,  0.2110,  1.2828,  0.8327,  8.055

tensor([ 0.4932,  0.4654,  0.7681,  4.0182,  2.8612,  3.7728,  0.7053,  0.3359,
         0.7384,  0.4456, -0.0341,  0.5586,  0.3575,  0.5857,  6.1559,  1.0209,
         2.1599,  0.2203,  0.9091,  0.3828], grad_fn=<SliceBackward0>)
tensor([-0.0344,  0.8232,  1.5571,  6.1637,  4.3073,  6.0480,  1.3526,  1.0675,
         0.5795,  1.0663,  0.2074,  0.0685,  0.2890,  0.6849,  9.4412,  0.0863,
        -0.1193,  1.1966,  0.5430, -0.0144])
tensor([0.3196, 0.6478, 1.1274, 6.2127, 5.9452, 6.9788, 0.6038, 0.4389, 1.0854,
        0.7854, 0.1580, 0.6520, 0.5815, 0.7107, 8.3364, 0.8994, 6.3098, 1.9177,
        2.7469, 0.8056], grad_fn=<SliceBackward0>)
tensor([ 1.2668,  0.5128,  1.0760,  8.0596,  4.5287,  5.1957, -0.7456, -1.2091,
        -0.6693, -0.3511, -0.7991, -0.1725, -0.6426, -0.5030, 11.0496,  3.0621,
         2.6112,  1.4603, -0.9668, -0.1881])
tensor([0.1554, 0.2677, 0.6108, 5.2366, 4.8387, 7.1025, 1.5520, 0.3511, 0.4159,
        1.0819, 0.0921, 0.2833, 0.4711, 0.3560, 2.3344, 0.6551, 5.65

tensor([0.2641, 0.3866, 0.8173, 6.2447, 6.3942, 8.6048, 2.4941, 0.2472, 0.6780,
        0.9030, 0.1077, 0.3697, 0.4037, 0.4014, 7.8372, 0.8778, 7.7530, 2.6113,
        3.7995, 0.5786], grad_fn=<SliceBackward0>)
tensor([-0.3197,  0.2555,  0.4818,  6.8701,  6.7302, 11.3960,  0.8834,  1.6079,
         0.4609,  1.9697, -0.0435, -0.2547, -0.0355,  0.3722,  1.4213,  5.6070,
         9.3830,  1.9320,  0.9660, -0.2134])
tensor([0.2007, 0.2891, 0.4176, 3.3013, 4.1590, 6.3022, 1.5733, 0.1909, 0.2482,
        0.7528, 0.1412, 0.2570, 0.3951, 0.2693, 3.2164, 0.4148, 5.3340, 1.7449,
        2.9486, 0.3274], grad_fn=<SliceBackward0>)
tensor([-0.4308,  0.4074,  1.6681,  2.7583,  4.1993,  6.3607,  0.3808,  1.4683,
         0.7877,  0.8517, -0.9740, -0.3014, -1.0364, -0.6925,  3.2571, -0.1657,
         3.9806,  2.4785,  5.4333, -0.2962])
tensor([0.3340, 0.3493, 0.6491, 4.7977, 4.9410, 6.8099, 1.4667, 0.2380, 0.5338,
        0.5490, 0.1169, 0.3328, 0.3275, 0.3777, 6.9947, 0.8141, 6.1317, 1.8755,
        

tensor([0.6422, 0.3852, 0.6467, 4.5821, 3.7356, 5.4377, 3.6449, 0.2696, 0.5143,
        0.2778, 0.0779, 0.3580, 0.3550, 0.3905, 8.5826, 1.0723, 3.9589, 0.9187,
        0.5607, 0.3939], grad_fn=<SliceBackward0>)
tensor([ 0.9652,  0.0924,  0.0443,  7.5377,  5.4499,  7.9445,  4.6032, -0.0344,
         0.1295,  0.8286,  1.1378, -0.3648, -0.1781,  0.2352, 14.0588, -0.2093,
         8.0773,  0.3894,  2.9986, -0.2854])
tensor([ 4.0055e-01,  9.9355e-01,  1.7375e+00,  7.4179e+00,  6.4049e+00,
         5.5699e+00,  5.6406e-01,  1.0571e+00,  1.7677e+00,  5.7339e-01,
        -3.9862e-03,  1.0944e+00,  7.9088e-01,  1.1248e+00,  1.0185e+01,
         8.0148e-01,  5.4432e+00,  1.4073e+00,  2.5202e+00,  7.4436e-01],
       grad_fn=<SliceBackward0>)
tensor([-0.7962, -0.5116, -1.0910,  7.4160,  7.4415,  3.2070, -0.5281, -1.7865,
         0.5745,  0.9842,  0.4285, -0.8843, -0.2844, -1.3877, 13.4009, -0.4968,
         1.6430,  2.9132, -0.1550, -0.5299])
tensor([ 0.4664,  0.5336,  1.0279,  7.8122,  6.4137, 

tensor([0.4593, 0.5798, 0.8853, 5.2446, 5.5615, 7.4017, 1.7989, 0.3927, 0.7805,
        0.9197, 0.2301, 0.5156, 0.5860, 0.5876, 6.3574, 1.0353, 6.8184, 2.5908,
        3.2548, 0.5455], grad_fn=<SliceBackward0>)
tensor([-7.7626e-02,  8.6022e-01,  1.5306e+00,  3.7593e+00,  5.1259e+00,
         6.7133e+00,  5.7423e+00,  1.4979e+00,  1.5081e+00,  3.8519e+00,
        -4.9651e-01,  2.0173e+00,  1.7400e+00, -9.9309e-03,  1.0820e+01,
         8.6081e-02,  4.3365e+00,  3.2738e+00,  9.2902e-01,  6.2568e-02])
tensor([0.1726, 0.3182, 0.4951, 3.5043, 3.8483, 6.9228, 1.5686, 0.2854, 0.3281,
        1.0097, 0.1460, 0.3069, 0.6281, 0.4287, 2.0935, 0.3473, 5.1006, 1.2131,
        3.4110, 0.2917], grad_fn=<SliceBackward0>)
tensor([-0.6738, -0.6016,  0.3310,  4.8677,  5.5072, 10.0489,  5.0883, -1.0546,
        -0.4242,  0.5665, -1.2455, -0.5663, -0.9253, -0.2442,  2.0373, -0.3605,
         6.8080,  0.9951,  0.8583, -0.4494])
tensor([ 0.1950,  0.3887,  0.9333,  4.8053,  3.4417,  5.1784,  0.5155,  0.3054,


tensor([0.2632, 0.1862, 0.4145, 4.8040, 4.1767, 6.9553, 4.1909, 0.0850, 0.2930,
        0.1040, 0.0279, 0.1868, 0.2842, 0.1868, 9.5012, 0.7133, 5.4035, 1.1806,
        0.7804, 0.2605], grad_fn=<SliceBackward0>)
tensor([ 0.4780, -0.5996,  0.4307,  5.0919,  6.0417,  7.1174,  0.6090,  0.3002,
         0.0362, -0.2943, -1.2905, -0.7176,  2.1358, -0.2718, 11.9006,  9.3964,
         2.7917, -0.0195,  0.4679, -0.5448])
tensor([0.3297, 0.5751, 0.9274, 4.4497, 4.4196, 5.5946, 0.0309, 0.4187, 0.8757,
        0.5636, 0.1611, 0.5686, 0.5384, 0.6440, 6.4548, 0.6438, 5.0259, 1.3058,
        1.7389, 0.7640], grad_fn=<SliceBackward0>)
tensor([ 1.7811,  0.9048,  1.3065,  6.6191,  3.4782,  5.7545,  1.0738,  0.1241,
         1.8160,  0.6853, -0.4608,  0.0219,  0.6779,  2.0324,  6.7636,  0.0934,
         7.7127,  2.4499, -0.4126, -0.0202])
tensor([ 0.6007,  0.6200,  1.0839,  5.6749,  5.6580, 11.1973,  6.4499,  0.4437,
         0.8204,  1.8782,  0.2561,  0.4594,  1.2341,  0.7360,  6.6608,  0.7760,
        

tensor([0.2735, 0.5521, 0.9841, 6.4498, 6.6523, 9.0079, 2.1840, 0.3998, 0.7584,
        1.6500, 0.2056, 0.4500, 0.7152, 0.5301, 4.9462, 0.9154, 7.7073, 1.8388,
        5.3869, 0.3236], grad_fn=<SliceBackward0>)
tensor([ 0.2423,  0.3492,  2.4894,  5.0637,  8.2651,  9.5164,  1.2188,  0.5198,
         0.1494,  2.7854,  1.6837,  0.4209,  2.2629,  1.4781,  5.8051,  0.4059,
         5.6683,  0.0871, 10.2402,  0.2264])
tensor([0.3888, 0.6817, 1.1694, 7.1238, 6.2326, 7.4858, 1.0075, 0.6387, 0.9102,
        1.6810, 0.2359, 0.5938, 0.8317, 0.7002, 2.7678, 1.1085, 6.9041, 0.3455,
        4.9395, 0.1666], grad_fn=<SliceBackward0>)
tensor([ 1.2921,  0.0614,  1.6454, 11.3643,  7.3988,  3.9879,  0.5581,  2.7590,
         2.8424,  0.9655,  0.8985, -0.1339,  1.4697,  2.4325, -0.1183, -0.0486,
         4.5731,  0.4256,  7.4933, -0.1696])
tensor([ 0.4902,  0.8053,  1.5171,  9.2265,  6.8101, 11.2683,  2.3751,  0.5484,
         1.5445,  0.7718,  0.1621,  0.8385,  0.8221,  1.0029, 17.0487,  2.1418,
        

tensor([ 0.4767,  0.6530,  1.2400,  7.5669,  7.2905, 12.1351,  5.2690,  0.4826,
         0.9400,  2.1573,  0.2477,  0.5027,  1.1322,  0.7407,  7.7308,  1.1402,
        10.1880,  4.3896,  6.6545,  0.4296], grad_fn=<SliceBackward0>)
tensor([-0.0401,  0.9337,  1.8568,  9.1172,  8.1701,  8.4997,  3.1268,  1.0201,
         2.0541, -0.0543,  2.2783,  2.0757,  0.9194,  0.0611,  6.7849,  0.1156,
        11.5881,  2.2148,  5.8576,  0.0963])
tensor([ 0.4358,  0.6593,  1.3572,  8.4937,  7.6072, 12.2285,  4.4856,  0.5694,
         1.0017,  2.4661,  0.2193,  0.4947,  1.2006,  0.7955,  6.8037,  1.2163,
        10.4309,  3.0980,  7.3006,  0.3354], grad_fn=<SliceBackward0>)
tensor([4.0762e-03, 1.2428e+00, 2.5070e+00, 5.3935e+00, 8.0098e+00, 7.8000e+00,
        3.7436e+00, 5.5493e-01, 7.3142e-01, 3.8202e+00, 3.9333e-01, 3.3469e-01,
        3.8895e+00, 1.2736e-01, 6.4153e+00, 2.3138e-01, 1.0424e+01, 4.3347e+00,
        8.3377e+00, 5.5459e-02])
tensor([ 0.7591,  0.4884,  1.0356,  7.7947,  7.3650, 11.1391

tensor([0.1235, 0.2587, 0.5410, 4.4361, 5.0644, 6.7448, 1.4004, 0.2299, 0.3867,
        0.9258, 0.1091, 0.2498, 0.3524, 0.2798, 3.2205, 0.5660, 5.6523, 1.0428,
        3.6289, 0.2655], grad_fn=<SliceBackward0>)
tensor([ 1.1861e+00, -8.0382e-02,  4.0367e-01,  2.9713e+00,  5.2272e+00,
         1.0091e+01,  1.5039e+00, -7.0869e-01,  3.2678e-01,  5.0718e-01,
         1.2522e+00,  9.5228e-03, -2.9454e-01,  1.3432e+00,  3.7407e-01,
         2.9939e+00,  7.4165e+00,  1.0516e+00,  4.8626e+00, -1.8452e-02])
tensor([ 0.1009,  0.6026,  1.0943,  4.7813,  2.6291,  5.9975,  0.3445,  0.3742,
         1.3034,  0.0687, -0.2924,  0.7068,  0.4213,  0.7488,  7.9143,  0.1679,
         2.8419,  0.0727,  0.6637,  0.4592], grad_fn=<SliceBackward0>)
tensor([ 0.5352,  0.4509,  1.4489,  4.2788,  2.9418,  4.1904,  0.6814, -0.7661,
         0.5250, -0.7892, -0.5752,  0.9190,  0.8118,  0.5547, 10.0446, -0.5191,
         2.3449, -0.6547, -1.0606, -0.5022])
tensor([ 0.3835,  0.7980,  1.4403,  6.7232,  6.3883,  5.0145


KeyboardInterrupt

