In [1]:
from models import *
from jepa import JEPA
from datasets import H5Dataset, SparseDataset
from trainer import Trainer

In [2]:
d1 = H5Dataset('train', 'multi')
d2 = H5Dataset('train', 'cite')

In [3]:
import pandas as pd

df1 = pd.read_hdf('data/train_cite_inputs.h5', start=1000, stop=2000)
df2 = pd.read_hdf('data/train_multi_targets.h5', start=1000, stop=2000)

rna1 = list(df1.keys())
rna2 = list(df2.keys())
df2.head()

gene_id       ENSG00000121410  ENSG00000268895  ENSG00000175899  \
cell_id                                                           
b31fa801888c         0.000000              0.0              0.0   
0e2c18dfbf7e         0.000000              0.0              0.0   
352aba65831c         4.535933              0.0              0.0   
53b116cbaf60         3.859019              0.0              0.0   
bb79553d92ea         4.181534              0.0              0.0   

gene_id       ENSG00000245105  ENSG00000166535  ENSG00000256661  \
cell_id                                                           
b31fa801888c              0.0              0.0              0.0   
0e2c18dfbf7e              0.0              0.0              0.0   
352aba65831c              0.0              0.0              0.0   
53b116cbaf60              0.0              0.0              0.0   
bb79553d92ea              0.0              0.0              0.0   

gene_id       ENSG00000184389  ENSG00000128274  ENSG00000094914  \
cell_id                                                           
b31fa801888c              0.0              0.0         0.000000   
0e2c18dfbf7e              0.0              0.0         4.449378   
352aba65831c              0.0              0.0         0.000000   
53b116cbaf60              0.0              0.0         4.541565   
bb79553d92ea              0.0              0.0         0.000000   

gene_id       ENSG00000081760  ...  ENSG00000086827  ENSG00000174442  \
cell_id                        ...                                     
b31fa801888c         5.560683  ...              0.0         0.000000   
0e2c18dfbf7e         4.449378  ...              0.0         0.000000   
352aba65831c         4.535933  ...              0.0         5.627375   
53b116cbaf60         3.859019  ...              0.0         0.000000   
bb79553d92ea         0.000000  ...              0.0         4.181534   

gene_id       ENSG00000122952  ENSG00000198205  ENSG00000198455  \
cell_id                                                           
b31fa801888c         0.000000              0.0         0.000000   
0e2c18dfbf7e         0.000000              0.0         0.000000   
352aba65831c         4.535933              0.0         4.535933   
53b116cbaf60         4.541565              0.0         0.000000   
bb79553d92ea         4.867014              0.0         4.181534   

gene_id       ENSG00000070476  ENSG00000203995  ENSG00000162378  \
cell_id                                                           
b31fa801888c         0.000000              0.0         0.000000   
0e2c18dfbf7e         5.136666              0.0         4.449378   
352aba65831c         4.535933              0.0         0.000000   
53b116cbaf60         4.541565              0.0         0.000000   
bb79553d92ea         0.000000              0.0         4.181534   

gene_id       ENSG00000159840  ENSG00000074755  
cell_id                                         
b31fa801888c         0.000000         0.000000  
0e2c18dfbf7e         0.000000         4.449378  
352aba65831c         0.000000         4.535933  
53b116cbaf60         0.000000         0.000000  
bb79553d92ea         4.181534         0.000000  

[5 rows x 23418 columns]

In [4]:
for i in range(len(rna1)):
    rna1[i] = rna1[i].split('_')[0]

count = 0
idxs_shared = []
idxs_not_shared = []
for i, s in enumerate(rna1):
    if s in rna2:
        idxs_shared.append(i)
    else:
        idxs_not_shared.append(i)

In [5]:
model = LinearCoder([18386, 3664], dropout=0.01, input_2d=False, days=[2])
count_parameters(model)

80805856

In [8]:
batch_size = 128
multi = d1.get_dataloader(batch_size)
cite = d2.get_dataloader(batch_size)
device = torch.device('cuda')
model.train().to(device)
optim = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=0.0001)
for (x, day), y in multi:
    optim.zero_grad()
    y = y.to(device)
    inputs, targets = y[:, idxs_shared], y[:, idxs_not_shared]
    out = model(inputs, [torch.tensor(2),] * batch_size)
    
    loss = F.mse_loss(out, targets)
    print(loss.item())
    loss.backward()
    optim.step()

481.1336975097656
69.7893295288086
288.26904296875
182.71786499023438
51.296058654785156
61.30269241333008
119.25382995605469
108.91669464111328
49.6721076965332
12.913922309875488
28.107383728027344
61.05895233154297
65.21923828125
40.998661041259766
13.460490226745605
6.199322700500488
18.001663208007812
27.915307998657227
22.043642044067383
8.861246109008789
5.799225330352783
7.084419250488281
4.288426876068115
6.590734958648682
3.511699914932251
5.621718883514404
3.513073205947876
4.808241844177246
3.263010025024414
3.6714444160461426
3.4507508277893066
2.987992763519287
3.611771583557129
2.593909978866577
3.3344204425811768
2.521364450454712
2.9738566875457764
2.5844411849975586
2.486013650894165
2.6499643325805664
2.2172036170959473
2.5241072177886963
2.113948345184326
2.3997490406036377
2.1546761989593506
2.282546281814575
2.0954434871673584
2.0233566761016846
2.0816762447357178
1.979690670967102
2.088170051574707
1.9303090572357178
2.0210485458374023
1.9058079719543457
2.001823

2.4890503883361816
2.315194845199585
1.9418705701828003
1.8288525342941284
2.089934825897217
2.4262757301330566
2.5062389373779297
2.3322298526763916
1.9976451396942139
1.8265964984893799
1.9467246532440186
2.160769462585449
2.2855374813079834
2.126659393310547
1.8829847574234009
1.8255258798599243
1.9051281213760376
1.8983421325683594
1.8524386882781982
1.8108296394348145
1.8659687042236328
1.8913286924362183
1.8290139436721802
1.8247488737106323
1.8797391653060913
1.972581386566162
1.956061601638794
1.8593621253967285
1.8294222354888916
1.8877042531967163
1.8911857604980469
1.8454960584640503
1.7957267761230469
1.8407933712005615
1.8163343667984009
1.8192687034606934
1.829115867614746
1.8006733655929565
1.8062412738800049
1.8273552656173706
1.8138006925582886
1.8233230113983154
1.848877191543579
1.8791141510009766
1.8751354217529297
1.855579137802124
1.8653225898742676
1.817650318145752
1.829240083694458
1.8543838262557983
1.8279949426651
1.819570541381836
1.8349761962890625
1.819664

In [11]:
model.eval()
val = H5Dataset('val', 'multi').get_dataloader(1)
for (x, day), y in val:
    y = y.to(device)
    inputs, targets = y[:, idxs_shared], y[:, idxs_not_shared]
    out = model(inputs, [torch.tensor(2),] * batch_size)
    
    loss = F.mse_loss(out, targets)
    print(out.squeeze()[:20])
    print(targets.squeeze()[:20])
    print(loss)
    

tensor([ 0.9411,  1.2949,  0.6009,  3.6289,  1.0904,  2.5381,  2.1024, -0.8175,
         2.6332,  2.4375,  1.4167, -0.8837,  2.2073, -1.0108,  1.1138,  2.1828,
        -1.0853,  1.4916, -0.9354, -1.0824], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 5.1311, 0.0000, 0.0000, 5.1311,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.8062, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.8953,  1.2650,  0.5159,  3.8400,  1.0427,  2.4912,  2.2449, -0.7427,
         2.6885,  2.4667,  1.3546, -0.8363,  2.3562, -0.9280,  1.0586,  2.3331,
        -1.0039,  1.6190, -0.9056, -1.0214], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0')
tensor(2.6027, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0348,  1.3838,  0.4971,  3.3005,  1.0878,  2

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        5.5625, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(3.0080, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0006,  1.3619,  0.5868,  3.6094,  1.0883,  2.5616,  2.3593, -0.8200,
         2.7032,  2.4823,  1.3539, -0.8989,  2.4193, -0.9894,  1.1314,  2.4051,
        -1.0769,  1.7293, -0.9793, -1.1128], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 5.4062, 0.0000, 6.3198, 5.4062, 0.0000, 0.0000,
        4.7175, 0.0000, 0.0000, 5.4062, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6311, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0116,  1.3790,  0.5753,  3.7572,  1.1052,  2.5035,  2.3645, -0.8176,
         2.7482,  2.4736,  1.3782, -0.9202,  2.4426, -0.9929,  1.1540,  2.4483,
        -1.0840,  1.7808, -1.0081, -1.1211], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 4.3202, 0.0000, 0.0000, 0.0000, 0.0000, 4.3202,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.3202, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5528, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0424,  1.4055,  0.5353,  3.5996,  1.1020,  2.5927,  2.6164, -0.8073,
         2.7339,  2.5248,  1.3646, -0.9195,  2.4762, -0.9895,  1.1581,  2.4517,
        -1.0877,  1.9168, -1.0077, -1.1375], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.4592,
        0.0000, 0.0000, 0.0000, 4.4592, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5433, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0255,  1.3844,  0.4782,  3.6243,  1.0726,  2.5719,  2.7837, -0.7536,
         2.7515,  2.5409,  1.2936, -0.8756,  2.5272, -0.9388,  1.1183,  2.5485,
        -1.0344,  1.9801, -0.9758, -1.0899], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 5.2238, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6826, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.1809,  1.5276,  0.5413,  3.5143,  1.1595,  2.6947,  3.1259, -0.8619,
         2.8285,  2.5898,  1.4195, -0.9875,  2.5078, -1.0293,  1.2496,  2.5434,
        -1.1585,  2.2809, -1.1134, -1.2443], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 4.6196, 0.0000, 3.9362, 4.6196, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.6196, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5062, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0275,  1.3505,  0.5524,  3.4930,  1.1094,  2.5986,  2.5339, -0.8082,
         2.6841,  2.4966,  1.3742, -0.8858,  2.2218, -1.0111,  1.1393,  2.3001,
        -1.1008,  1.6860, -0.9629, -1.1195], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 5.3719, 0.0000, 4.6834, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.7616, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0070,  1.4026,  0.5509,  4.2160,  1.1682,  2.5504,  2.4477, -0.8409,
         2.8281,  2.5526,  1.6417, -0.9938,  2.3557, -1.0421,  1.2117,  2.2719,
        -1.1585,  1.9493, -1.0726, -1.1945], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 5.7770, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.7586, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0394,  1.4083,  0.5657,  3.6476,  1.1289,  2.4956,  2.3781, -0.8119,
         2.7225,  2.4798,  1.3494, -0.9431,  2.4902, -1.0203,  1.1728,  2.4873,
        -1.1043,  1.7666, -1.0150, -1.1313], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 5.3823, 0.0000, 5.3823, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6373, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0597,  1.4081,  0.5286,  3.8891,  1.1485,  2.6213,  2.7565, -0.8232,
         2.8136,  2.5665,  1.5152, -0.9461,  2.3202, -1.0164,  1.1868,  2.3622,
        -1.1322,  1.9796, -1.0468, -1.1828], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.4596, 0.0000, 5.1470,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.7061, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9540,  1.3236,  0.5029,  3.8022,  1.0610,  2.5060,  2.4652, -0.7536,
         2.7310,  2.4910,  1.3461, -0.8637,  2.4260, -0.9364,  1.0938,  2.4249,
        -1.0245,  1.7940, -0.9500, -1.0603], device='cuda:0',

tensor([4.7155, 0.0000, 0.0000, 4.7155, 0.0000, 0.0000, 4.7155, 0.0000, 0.0000,
        0.0000, 0.0000, 4.7155, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6063, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0775,  1.4339,  0.5772,  3.4651,  1.1198,  2.5886,  2.5816, -0.8335,
         2.7184,  2.5052,  1.3337, -0.9387,  2.4969, -1.0155,  1.1799,  2.4901,
        -1.1095,  1.8861, -1.0286, -1.1584], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 0.0000, 4.6707, 0.0000, 4.6707, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 6.0500, 0.0000, 0.0000, 5.3592, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5678, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9557,  1.3355,  0.4984,  3.9756,  1.0803,  2.5066,  2.4727, -0.7580,
         2.7720,  2.5159,  1.4051, -0.8865,  2.4558, -0.9462,  1.1107,  2.4352,
        -1.0393,  1.8474, -0.9704, -1.0759], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 5.8794, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6906, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0352,  1.3704,  0.5376,  3.6123,  1.0965,  2.5980,  2.6601, -0.7985,
         2.7435,  2.5198,  1.3559, -0.8864,  2.3564, -0.9777,  1.1345,  2.4273,
        -1.0757,  1.8371, -0.9867, -1.1208], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 4.7276, 0.0000, 0.0000, 0.0000, 0.0000, 4.7276,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 5.4163, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6357, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.1118,  1.4415,  0.5969,  3.3494,  1.1519,  2.6360,  2.6161, -0.8673,
         2.6965,  2.5001,  1.3981, -0.9581,  2.3021, -1.0618,  1.2138,  2.3394,
        -1.1630,  1.8282, -1.0406, -1.1976], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        4.7175, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.7175, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5095, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9725,  1.3357,  0.5170,  3.6988,  1.0670,  2.5441,  2.4822, -0.7670,
         2.7135,  2.5003,  1.3422, -0.8703,  2.4276, -0.9505,  1.1012,  2.4162,
        -1.0385,  1.7891, -0.9528, -1.0765], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 4.6527, 0.0000, 4.6527, 0.0000, 0.0000, 0.0000,
        4.6527, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6212, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0490,  1.4247,  0.5615,  3.8896,  1.1466,  2.5727,  2.5503, -0.8374,
         2.7948,  2.5352,  1.5000, -0.9701,  2.4377, -1.0252,  1.1986,  2.3985,
        -1.1324,  1.9516, -1.0617, -1.1832], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 5.1242, 0.0000, 4.4370, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.4370, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.8605, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9581,  1.3186,  0.5248,  3.6770,  1.0687,  2.5030,  2.3576, -0.7600,
         2.6910,  2.4767,  1.3141, -0.8614,  2.4031, -0.9563,  1.0938,  2.4149,
        -1.0337,  1.6701, -0.9311, -1.0534], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 4.9874, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.9874, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6373, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0403,  1.4130,  0.5421,  3.8740,  1.1142,  2.5750,  2.6393, -0.8203,
         2.8121,  2.5384,  1.4462, -0.9370,  2.4778, -0.9843,  1.1755,  2.4624,
        -1.0946,  2.0135, -1.0432, -1.1575], device='cuda:0',

       grad_fn=<SliceBackward0>)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0')
tensor(2.4549, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9347,  1.3157,  0.5009,  3.9792,  1.0883,  2.4836,  2.3497, -0.7524,
         2.7393,  2.5030,  1.4218, -0.8869,  2.3968, -0.9621,  1.1066,  2.3710,
        -1.0479,  1.7362, -0.9530, -1.0654], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 4.8591, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.6320, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9818,  1.3439,  0.5721,  3.5547,  1.0864,  2.5050,  2.2307, -0.7974,
         2.6610,  2.4539,  1.3065, -0.8921,  2.4238, -0.9933,  1.1182,  2.4119,
        -1.0685,  1.6103, -0.9523, -1.0828], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0., 0., 0., 0.

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        4.8344, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.8344,
        0.0000, 0.0000], device='cuda:0')
tensor(2.7059, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0258,  1.3930,  0.5150,  3.8117,  1.1049,  2.5809,  2.6881, -0.7922,
         2.7826,  2.5449,  1.4171, -0.9156,  2.4597, -0.9737,  1.1496,  2.4524,
        -1.0781,  1.9786, -1.0153, -1.1339], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 4.5340, 0.0000, 4.5340, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 4.5340, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.4604, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0823,  1.4311,  0.6105,  3.1790,  1.1088,  2.5834,  2.3837, -0.8529,
         2.6361,  2.4620,  1.2570, -0.9349,  2.4799, -1.0355,  1.1766,  2.4645,
        -1.1202,  1.7100, -1.0041, -1.1509], device='cuda:0',

tensor(2.3938, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0651,  1.4245,  0.5351,  3.7302,  1.1105,  2.5832,  2.7317, -0.8133,
         2.8037,  2.5397,  1.3797, -0.9238,  2.4963, -0.9803,  1.1730,  2.5269,
        -1.0878,  2.0157, -1.0356, -1.1508], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 4.3317, 0.0000, 0.0000, 4.3317, 0.0000, 5.0183,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5590, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0082,  1.3659,  0.5682,  3.8190,  1.1294,  2.5557,  2.4203, -0.8265,
         2.7452,  2.4989,  1.4823, -0.9293,  2.2788, -1.0212,  1.1687,  2.2901,
        -1.1181,  1.7658, -1.0071, -1.1432], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 5.6314, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        

tensor([0.0000, 0.0000, 0.0000, 4.4452, 0.0000, 4.4452, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5601, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9803,  1.3549,  0.6164,  3.7575,  1.1263,  2.4552,  2.0227, -0.8343,
         2.6883,  2.4318,  1.4154, -0.9357,  2.3516, -1.0377,  1.1618,  2.3312,
        -1.1139,  1.5447, -0.9888, -1.1130], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 5.3297, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        6.0204, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 5.3297, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.9081, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 0.9455,  1.2969,  0.5226,  3.7133,  1.0561,  2.5408,  2.4435, -0.7659,
         2.6998,  2.4783,  1.3668, -0.8465,  2.2926, -0.9432,  1.0874,  2.3110,
        -1.0311,  1.7168, -0.9302, -1.0573], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.5452, 4.5452, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.7599, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0088,  1.3855,  0.5297,  4.0436,  1.1193,  2.5457,  2.5785, -0.8082,
         2.8234,  2.5343,  1.5041, -0.9351,  2.4046, -0.9836,  1.1694,  2.3936,
        -1.0934,  1.9718, -1.0352, -1.1452], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 5.8847, 0.0000, 0.0000, 4.5067, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.5447, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0371,  1.3750,  0.5923,  3.6233,  1.1323,  2.5693,  2.4392, -0.8350,
         2.7160,  2.4864,  1.4147, -0.9227,  2.2739, -1.0315,  1.1639,  2.3333,
        -1.1228,  1.6998, -1.0035, -1.1458], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 4.6745, 0.0000, 0.0000, 0.0000, 0.0000, 4.6745,
        4.6745, 0.0000, 4.6745, 4.6745, 0.0000, 0.0000, 4.6745, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.7816, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0395,  1.4011,  0.5748,  3.7199,  1.1168,  2.5363,  2.4734, -0.8256,
         2.7619,  2.4943,  1.3869, -0.9296,  2.4392, -1.0019,  1.1704,  2.4583,
        -1.0980,  1.8392, -1.0224, -1.1398], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([4.7301, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.7424, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0862,  1.4472,  0.5313,  3.6191,  1.1201,  2.6019,  2.7745, -0.8145,
         2.7798,  2.5495,  1.3556, -0.9399,  2.5475, -0.9944,  1.1805,  2.5562,
        -1.1009,  2.0336, -1.0416, -1.1631], device='cuda:0',

tensor([0.0000, 0.0000, 0.0000, 5.8663, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        4.4885, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 4.4885, 0.0000, 0.0000,
        0.0000, 0.0000], device='cuda:0')
tensor(2.3625, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0549,  1.4168,  0.5359,  3.6874,  1.1108,  2.5868,  2.6883, -0.8108,
         2.7733,  2.5351,  1.3806, -0.9252,  2.4871, -0.9874,  1.1663,  2.4927,
        -1.0902,  1.9763, -1.0252, -1.1466], device='cuda:0',
       grad_fn=<SliceBackward0>)
tensor([0.0000, 0.0000, 0.0000, 5.4799, 4.3896, 4.3896, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        4.3896, 0.0000], device='cuda:0')
tensor(2.5109, device='cuda:0', grad_fn=<MseLossBackward0>)
tensor([ 1.0708,  1.4232,  0.5469,  3.8674,  1.1464,  2.6283,  2.7664, -0.8386,
         2.8219,  2.5618,  1.5229, -0.9553,  2.3390, -1.0162,  1.2009,  2.3616,
        -1.1363,  2.0309, -1.0634, -1.1949], device='cuda:0',

KeyboardInterrupt: 